export interface FoodItem {
  name: string;
  kcal: number;
  category: string;
}

export const FOOD_DATABASE: FoodItem[] = [
  // ── 和食 ──────────────────────────────────
  { name: "焼き魚定食", kcal: 500, category: "和食" },
  { name: "肉じゃが定食", kcal: 550, category: "和食" },
  { name: "唐揚げ定食", kcal: 750, category: "和食" },
  { name: "天ぷら定食", kcal: 800, category: "和食" },
  { name: "刺身定食", kcal: 500, category: "和食" },
  { name: "豚汁定食", kcal: 600, category: "和食" },
  { name: "親子丼", kcal: 650, category: "和食" },
  { name: "カツ丼", kcal: 900, category: "和食" },
  { name: "牛丼（並）", kcal: 660, category: "和食" },
  { name: "牛丼（大盛）", kcal: 830, category: "和食" },
  { name: "牛丼（特盛）", kcal: 980, category: "和食" },
  { name: "天丼", kcal: 850, category: "和食" },
  { name: "海鮮丼", kcal: 600, category: "和食" },
  { name: "うな丼", kcal: 780, category: "和食" },
  { name: "鮭定食", kcal: 520, category: "和食" },
  { name: "さば定食", kcal: 560, category: "和食" },
  { name: "豚の生姜焼き定食", kcal: 700, category: "和食" },
  { name: "鶏の照り焼き定食", kcal: 680, category: "和食" },
  { name: "回鍋肉定食", kcal: 720, category: "和食" },
  { name: "麻婆豆腐定食", kcal: 650, category: "和食" },
  { name: "うどん（かけ）", kcal: 300, category: "和食" },
  { name: "うどん（天ぷら）", kcal: 500, category: "和食" },
  { name: "うどん（肉）", kcal: 450, category: "和食" },
  { name: "そば（もり）", kcal: 320, category: "和食" },
  { name: "そば（天ぷら）", kcal: 520, category: "和食" },
  { name: "そば（肉）", kcal: 430, category: "和食" },
  { name: "ラーメン（醤油）", kcal: 450, category: "和食" },
  { name: "ラーメン（味噌）", kcal: 550, category: "和食" },
  { name: "ラーメン（塩）", kcal: 420, category: "和食" },
  { name: "ラーメン（豚骨）", kcal: 580, category: "和食" },
  { name: "チャーシュー麺", kcal: 620, category: "和食" },
  { name: "つけ麺", kcal: 700, category: "和食" },
  { name: "冷やし中華", kcal: 550, category: "和食" },
  { name: "焼きそば", kcal: 500, category: "和食" },
  { name: "お好み焼き", kcal: 560, category: "和食" },
  { name: "たこ焼き（8個）", kcal: 300, category: "和食" },
  { name: "おでん（5品）", kcal: 300, category: "和食" },
  { name: "肉うどん", kcal: 450, category: "和食" },
  { name: "カレーうどん", kcal: 500, category: "和食" },
  { name: "ざるそば", kcal: 340, category: "和食" },
  { name: "すき焼き定食", kcal: 850, category: "和食" },
  { name: "しゃぶしゃぶ定食", kcal: 700, category: "和食" },
  { name: "焼き鳥（5本）", kcal: 350, category: "和食" },
  { name: "寿司（10貫）", kcal: 500, category: "和食" },
  { name: "手巻き寿司", kcal: 400, category: "和食" },
  { name: "茶碗蒸し", kcal: 80, category: "和食" },
  { name: "味噌汁", kcal: 40, category: "和食" },
  { name: "白米（1杯）", kcal: 260, category: "和食" },
  { name: "白米（大盛）", kcal: 390, category: "和食" },
  { name: "おにぎり（梅）", kcal: 170, category: "和食" },
  { name: "おにぎり（鮭）", kcal: 190, category: "和食" },
  { name: "おにぎり（ツナマヨ）", kcal: 210, category: "和食" },
  { name: "おにぎり（昆布）", kcal: 175, category: "和食" },
  { name: "おにぎり（焼きたらこ）", kcal: 185, category: "和食" },
  { name: "おにぎり（おかか）", kcal: 180, category: "和食" },
  { name: "冷奴", kcal: 80, category: "和食" },
  { name: "納豆ご飯", kcal: 330, category: "和食" },
  { name: "卵かけご飯", kcal: 310, category: "和食" },
  { name: "チキン南蛮", kcal: 600, category: "和食" },
  { name: "ざるうどん", kcal: 280, category: "和食" },
  { name: "冷やしうどん", kcal: 350, category: "和食" },

  // ── 洋食 ──────────────────────────────────
  { name: "ハンバーグ定食", kcal: 850, category: "洋食" },
  { name: "チキンソテー定食", kcal: 700, category: "洋食" },
  { name: "オムライス", kcal: 750, category: "洋食" },
  { name: "ハヤシライス", kcal: 800, category: "洋食" },
  { name: "カレーライス", kcal: 900, category: "洋食" },
  { name: "カレーライス（大盛）", kcal: 1100, category: "洋食" },
  { name: "ナポリタン", kcal: 650, category: "洋食" },
  { name: "グラタン", kcal: 550, category: "洋食" },
  { name: "コロッケ定食", kcal: 700, category: "洋食" },
  { name: "エビフライ定食", kcal: 800, category: "洋食" },
  { name: "ビーフシチュー定食", kcal: 750, category: "洋食" },
  { name: "パスタ（トマトソース）", kcal: 550, category: "洋食" },
  { name: "パスタ（カルボナーラ）", kcal: 800, category: "洋食" },
  { name: "パスタ（ペペロンチーノ）", kcal: 600, category: "洋食" },
  { name: "パスタ（ボロネーゼ）", kcal: 700, category: "洋食" },
  { name: "ピザ（マルゲリータ1枚）", kcal: 700, category: "洋食" },
  { name: "ピザ（クワトロフォルマッジ1枚）", kcal: 850, category: "洋食" },
  { name: "ピザ（テリヤキチキン1枚）", kcal: 800, category: "洋食" },
  { name: "ドリア", kcal: 600, category: "洋食" },
  { name: "シーフードドリア", kcal: 650, category: "洋食" },
  { name: "クリームシチュー", kcal: 450, category: "洋食" },
  { name: "ポークソテー", kcal: 550, category: "洋食" },
  { name: "ステーキ（150g）", kcal: 400, category: "洋食" },
  { name: "ポトフ", kcal: 250, category: "洋食" },
  { name: "ミートソーススパゲッティ", kcal: 700, category: "洋食" },
  { name: "クラムチャウダー", kcal: 200, category: "洋食" },
  { name: "ハムエッグ", kcal: 280, category: "洋食" },
  { name: "スクランブルエッグ", kcal: 200, category: "洋食" },
  { name: "目玉焼き", kcal: 100, category: "洋食" },
  { name: "フレンチトースト", kcal: 380, category: "洋食" },
  { name: "パンケーキ（2枚）", kcal: 420, category: "洋食" },

  // ── 中華 ──────────────────────────────────
  { name: "餃子定食", kcal: 650, category: "中華" },
  { name: "酢豚定食", kcal: 700, category: "中華" },
  { name: "チャーハン", kcal: 700, category: "中華" },
  { name: "八宝菜定食", kcal: 600, category: "中華" },
  { name: "エビチリ定食", kcal: 620, category: "中華" },
  { name: "中華丼", kcal: 680, category: "中華" },
  { name: "天津飯", kcal: 650, category: "中華" },
  { name: "担々麺", kcal: 700, category: "中華" },
  { name: "冷麺", kcal: 450, category: "中華" },
  { name: "小籠包（5個）", kcal: 250, category: "中華" },
  { name: "春巻き（2本）", kcal: 300, category: "中華" },
  { name: "シュウマイ（5個）", kcal: 200, category: "中華" },
  { name: "焼き餃子（6個）", kcal: 280, category: "中華" },
  { name: "揚げ餃子（6個）", kcal: 380, category: "中華" },
  { name: "水餃子（6個）", kcal: 200, category: "中華" },
  { name: "青椒肉絲定食", kcal: 680, category: "中華" },
  { name: "棒棒鶏", kcal: 280, category: "中華" },
  { name: "バンバンジー", kcal: 250, category: "中華" },
  { name: "チンジャオロース", kcal: 350, category: "中華" },
  { name: "台湾まぜそば", kcal: 750, category: "中華" },

  // ── ファストフード ──────────────────────────
  { name: "ビッグマック", kcal: 525, category: "ファストフード" },
  { name: "マックフライポテト（M）", kcal: 410, category: "ファストフード" },
  { name: "マックフライポテト（L）", kcal: 517, category: "ファストフード" },
  { name: "マックフライポテト（S）", kcal: 225, category: "ファストフード" },
  { name: "チーズバーガー", kcal: 302, category: "ファストフード" },
  { name: "てりやきマックバーガー", kcal: 473, category: "ファストフード" },
  { name: "フィレオフィッシュ", kcal: 377, category: "ファストフード" },
  { name: "マックナゲット（5個）", kcal: 270, category: "ファストフード" },
  { name: "マックシェイク（M）", kcal: 430, category: "ファストフード" },
  { name: "エッグマックマフィン", kcal: 303, category: "ファストフード" },
  { name: "ソーセージマフィン", kcal: 370, category: "ファストフード" },
  { name: "ホットケーキ（マクドナルド）", kcal: 460, category: "ファストフード" },
  { name: "モスバーガー", kcal: 417, category: "ファストフード" },
  { name: "テリヤキバーガー（MOS）", kcal: 380, category: "ファストフード" },
  { name: "ライスバーガー（MOS）", kcal: 350, category: "ファストフード" },
  { name: "フレッシュネスバーガー", kcal: 450, category: "ファストフード" },
  { name: "ケンタッキーオリジナルチキン（1ピース）", kcal: 237, category: "ファストフード" },
  { name: "ケンタッキー2ピースセット", kcal: 700, category: "ファストフード" },
  { name: "ケンタッキーサンダーチキン", kcal: 350, category: "ファストフード" },
  { name: "ケンタッキーポテト（M）", kcal: 280, category: "ファストフード" },
  { name: "サブウェイ（BLT）", kcal: 360, category: "ファストフード" },
  { name: "サブウェイ（ツナ）", kcal: 440, category: "ファストフード" },
  { name: "サブウェイ（チキン）", kcal: 380, category: "ファストフード" },
  { name: "吉野家 牛丼（並）", kcal: 652, category: "ファストフード" },
  { name: "吉野家 牛丼（大盛）", kcal: 826, category: "ファストフード" },
  { name: "すき家 牛丼（並）", kcal: 680, category: "ファストフード" },
  { name: "松屋 牛めし（並）", kcal: 641, category: "ファストフード" },
  { name: "松屋 定食（カルビ）", kcal: 800, category: "ファストフード" },
  { name: "なか卯 牛丼（並）", kcal: 615, category: "ファストフード" },
  { name: "サーティワン（シングル）", kcal: 200, category: "ファストフード" },
  { name: "ミスタードーナツ（ポンデリング）", kcal: 220, category: "ファストフード" },
  { name: "ミスタードーナツ（エンゼルクリーム）", kcal: 230, category: "ファストフード" },
  { name: "マクドナルドアップルパイ", kcal: 240, category: "ファストフード" },

  // ── コンビニ ──────────────────────────────
  { name: "コンビニ おにぎり（梅）", kcal: 175, category: "コンビニ" },
  { name: "コンビニ おにぎり（鮭）", kcal: 195, category: "コンビニ" },
  { name: "コンビニ おにぎり（ツナマヨ）", kcal: 215, category: "コンビニ" },
  { name: "コンビニ おにぎり（明太子）", kcal: 185, category: "コンビニ" },
  { name: "コンビニ おにぎり（海苔弁）", kcal: 200, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（ミックス）", kcal: 380, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（ツナ）", kcal: 350, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（BLT）", kcal: 370, category: "コンビニ" },
  { name: "コンビニ 幕の内弁当", kcal: 650, category: "コンビニ" },
  { name: "コンビニ 焼肉弁当", kcal: 750, category: "コンビニ" },
  { name: "コンビニ から揚げ弁当", kcal: 850, category: "コンビニ" },
  { name: "コンビニ のり弁当", kcal: 600, category: "コンビニ" },
  { name: "コンビニ チャーシュー弁当", kcal: 700, category: "コンビニ" },
  { name: "コンビニ から揚げ（3個）", kcal: 250, category: "コンビニ" },
  { name: "コンビニ ホットスナック（フランクフルト）", kcal: 260, category: "コンビニ" },
  { name: "コンビニ ホットスナック（コロッケ）", kcal: 200, category: "コンビニ" },
  { name: "コンビニ 肉まん", kcal: 230, category: "コンビニ" },
  { name: "コンビニ あんまん", kcal: 280, category: "コンビニ" },
  { name: "コンビニ ピザまん", kcal: 250, category: "コンビニ" },
  { name: "コンビニ カップラーメン（醤油）", kcal: 350, category: "コンビニ" },
  { name: "コンビニ カップラーメン（塩）", kcal: 320, category: "コンビニ" },
  { name: "コンビニ カップ焼きそば", kcal: 480, category: "コンビニ" },
  { name: "コンビニ チルドラーメン", kcal: 500, category: "コンビニ" },
  { name: "コンビニ サラダ（シーザー）", kcal: 150, category: "コンビニ" },
  { name: "コンビニ サラダ（和風）", kcal: 100, category: "コンビニ" },
  { name: "コンビニ ゆで卵（2個）", kcal: 150, category: "コンビニ" },
  { name: "コンビニ チーズ（6Pチーズ）", kcal: 200, category: "コンビニ" },
  { name: "コンビニ ヨーグルト（小）", kcal: 100, category: "コンビニ" },
  { name: "コンビニ プリン", kcal: 180, category: "コンビニ" },
  { name: "コンビニ シュークリーム", kcal: 250, category: "コンビニ" },
  { name: "コンビニ エクレア", kcal: 270, category: "コンビニ" },
  { name: "コンビニ ロールケーキ", kcal: 300, category: "コンビニ" },

  // ── お菓子・スイーツ ────────────────────────
  { name: "ショートケーキ", kcal: 350, category: "お菓子" },
  { name: "チョコレートケーキ", kcal: 420, category: "お菓子" },
  { name: "チーズケーキ", kcal: 380, category: "お菓子" },
  { name: "モンブラン", kcal: 400, category: "お菓子" },
  { name: "シュークリーム", kcal: 250, category: "お菓子" },
  { name: "エクレア", kcal: 270, category: "お菓子" },
  { name: "プリン", kcal: 180, category: "お菓子" },
  { name: "ティラミス", kcal: 400, category: "お菓子" },
  { name: "マカロン（1個）", kcal: 90, category: "お菓子" },
  { name: "クレープ（生クリーム）", kcal: 380, category: "お菓子" },
  { name: "クレープ（チョコバナナ）", kcal: 450, category: "お菓子" },
  { name: "ワッフル", kcal: 350, category: "お菓子" },
  { name: "アイスクリーム（バニラ）", kcal: 180, category: "お菓子" },
  { name: "アイスクリーム（チョコ）", kcal: 200, category: "お菓子" },
  { name: "ソフトクリーム", kcal: 220, category: "お菓子" },
  { name: "かき氷", kcal: 150, category: "お菓子" },
  { name: "ハーゲンダッツ（バニラ）", kcal: 244, category: "お菓子" },
  { name: "明治チョコレート（1枚50g）", kcal: 280, category: "お菓子" },
  { name: "ポッキー（1袋）", kcal: 240, category: "お菓子" },
  { name: "じゃがりこ（1個）", kcal: 178, category: "お菓子" },
  { name: "ポテトチップス（1袋60g）", kcal: 340, category: "お菓子" },
  { name: "コアラのマーチ（1箱）", kcal: 240, category: "お菓子" },
  { name: "グミ（1袋）", kcal: 200, category: "お菓子" },
  { name: "キャラメル（1袋）", kcal: 220, category: "お菓子" },
  { name: "おかき（1袋）", kcal: 180, category: "お菓子" },
  { name: "せんべい（5枚）", kcal: 200, category: "お菓子" },
  { name: "かっぱえびせん（1袋）", kcal: 200, category: "お菓子" },
  { name: "チョコパイ（1個）", kcal: 170, category: "お菓子" },
  { name: "ビスケット（1袋）", kcal: 250, category: "お菓子" },
  { name: "クッキー（3枚）", kcal: 180, category: "お菓子" },
  { name: "ドーナツ（1個）", kcal: 270, category: "お菓子" },
  { name: "シュガードーナツ", kcal: 250, category: "お菓子" },
  { name: "チョコドーナツ", kcal: 300, category: "お菓子" },
  { name: "どら焼き", kcal: 220, category: "お菓子" },
  { name: "たい焼き", kcal: 200, category: "お菓子" },
  { name: "大福（1個）", kcal: 220, category: "お菓子" },
  { name: "桜餅", kcal: 190, category: "お菓子" },
  { name: "みたらし団子（3本）", kcal: 280, category: "お菓子" },
  { name: "羊羹（1切れ）", kcal: 180, category: "お菓子" },
  { name: "わらび餅", kcal: 160, category: "お菓子" },
  { name: "チュロス（1本）", kcal: 200, category: "お菓子" },
  { name: "バウムクーヘン（1切れ）", kcal: 180, category: "お菓子" },
  { name: "フィナンシェ（1個）", kcal: 150, category: "お菓子" },
  { name: "マドレーヌ（1個）", kcal: 160, category: "お菓子" },
  { name: "カントリーマアム（1枚）", kcal: 65, category: "お菓子" },
  { name: "コアラのマーチ（1粒）", kcal: 12, category: "お菓子" },
  { name: "明治ガルボ（1袋）", kcal: 290, category: "お菓子" },
  { name: "柿の種（1袋）", kcal: 230, category: "お菓子" },
  { name: "チョコアイス（1本）", kcal: 200, category: "お菓子" },
  { name: "アイスバー（サイダー）", kcal: 100, category: "お菓子" },
  { name: "ガリガリ君", kcal: 70, category: "お菓子" },

  // ── パン ──────────────────────────────────
  { name: "食パン（1枚）", kcal: 160, category: "パン" },
  { name: "食パン（2枚）", kcal: 320, category: "パン" },
  { name: "トースト（1枚）", kcal: 180, category: "パン" },
  { name: "バタートースト（1枚）", kcal: 230, category: "パン" },
  { name: "ジャムトースト（1枚）", kcal: 210, category: "パン" },
  { name: "クロワッサン（1個）", kcal: 230, category: "パン" },
  { name: "メロンパン", kcal: 380, category: "パン" },
  { name: "クリームパン", kcal: 280, category: "パン" },
  { name: "あんパン", kcal: 300, category: "パン" },
  { name: "カレーパン", kcal: 350, category: "パン" },
  { name: "コロネ（チョコ）", kcal: 280, category: "パン" },
  { name: "ハムサンド", kcal: 280, category: "パン" },
  { name: "ツナサンド", kcal: 300, category: "パン" },
  { name: "タマゴサンド", kcal: 320, category: "パン" },
  { name: "ホットドッグ", kcal: 350, category: "パン" },
  { name: "バーガーバンズ（1個）", kcal: 150, category: "パン" },
  { name: "ベーグル（1個）", kcal: 280, category: "パン" },
  { name: "イングリッシュマフィン（1個）", kcal: 130, category: "パン" },
  { name: "フランスパン（1切れ）", kcal: 110, category: "パン" },
  { name: "ロールパン（1個）", kcal: 100, category: "パン" },
  { name: "チーズパン", kcal: 260, category: "パン" },
  { name: "シナモンロール", kcal: 350, category: "パン" },
  { name: "デニッシュ（1個）", kcal: 280, category: "パン" },

  // ── 飲み物 ────────────────────────────────
  { name: "コーヒー（ブラック）", kcal: 5, category: "飲み物" },
  { name: "カフェラテ（M）", kcal: 170, category: "飲み物" },
  { name: "カフェラテ（L）", kcal: 220, category: "飲み物" },
  { name: "カプチーノ", kcal: 130, category: "飲み物" },
  { name: "カフェモカ", kcal: 260, category: "飲み物" },
  { name: "キャラメルマキアート", kcal: 280, category: "飲み物" },
  { name: "抹茶ラテ", kcal: 200, category: "飲み物" },
  { name: "ほうじ茶ラテ", kcal: 180, category: "飲み物" },
  { name: "コーヒーフラペチーノ（スタバ）", kcal: 320, category: "飲み物" },
  { name: "ダブルチョコチップフラペチーノ（スタバ）", kcal: 480, category: "飲み物" },
  { name: "スタバ抹茶クリームフラペチーノ", kcal: 440, category: "飲み物" },
  { name: "スタバキャラメルフラペチーノ", kcal: 380, category: "飲み物" },
  { name: "緑茶（無糖）", kcal: 0, category: "飲み物" },
  { name: "紅茶（無糖）", kcal: 5, category: "飲み物" },
  { name: "麦茶（無糖）", kcal: 0, category: "飲み物" },
  { name: "ミルクティー（500ml）", kcal: 200, category: "飲み物" },
  { name: "ペットボトル緑茶（500ml）", kcal: 5, category: "飲み物" },
  { name: "ペットボトルお茶（加糖）", kcal: 100, category: "飲み物" },
  { name: "コカ・コーラ（500ml）", kcal: 225, category: "飲み物" },
  { name: "コカ・コーラ ゼロ（500ml）", kcal: 0, category: "飲み物" },
  { name: "ファンタ（500ml）", kcal: 230, category: "飲み物" },
  { name: "スプライト（500ml）", kcal: 210, category: "飲み物" },
  { name: "オレンジジュース（200ml）", kcal: 90, category: "飲み物" },
  { name: "リンゴジュース（200ml）", kcal: 90, category: "飲み物" },
  { name: "野菜ジュース（200ml）", kcal: 70, category: "飲み物" },
  { name: "牛乳（200ml）", kcal: 135, category: "飲み物" },
  { name: "豆乳（200ml）", kcal: 110, category: "飲み物" },
  { name: "アーモンドミルク（200ml）", kcal: 60, category: "飲み物" },
  { name: "スポーツドリンク（500ml）", kcal: 125, category: "飲み物" },
  { name: "アクエリアス（500ml）", kcal: 100, category: "飲み物" },
  { name: "ポカリスエット（500ml）", kcal: 130, category: "飲み物" },
  { name: "エナジードリンク（モンスター 355ml）", kcal: 160, category: "飲み物" },
  { name: "Red Bull（250ml）", kcal: 115, category: "飲み物" },
  { name: "コーヒー缶（加糖）", kcal: 80, category: "飲み物" },
  { name: "ビール（350ml）", kcal: 150, category: "飲み物" },
  { name: "ビール（500ml）", kcal: 215, category: "飲み物" },
  { name: "発泡酒（350ml）", kcal: 140, category: "飲み物" },
  { name: "ハイボール（350ml）", kcal: 100, category: "飲み物" },
  { name: "チューハイ（350ml）", kcal: 160, category: "飲み物" },
  { name: "ワイン（グラス1杯）", kcal: 90, category: "飲み物" },
  { name: "日本酒（1合）", kcal: 200, category: "飲み物" },
  { name: "焼酎ロック（1杯）", kcal: 130, category: "飲み物" },
  { name: "水・お茶（無糖）", kcal: 0, category: "飲み物" },
  { name: "プロテインシェイク", kcal: 200, category: "飲み物" },
  { name: "甘酒（200ml）", kcal: 100, category: "飲み物" },

  // ── 果物 ──────────────────────────────────
  { name: "バナナ（1本）", kcal: 90, category: "果物" },
  { name: "りんご（1個）", kcal: 150, category: "果物" },
  { name: "みかん（1個）", kcal: 45, category: "果物" },
  { name: "オレンジ（1個）", kcal: 80, category: "果物" },
  { name: "いちご（10粒）", kcal: 40, category: "果物" },
  { name: "ぶどう（1房）", kcal: 120, category: "果物" },
  { name: "スイカ（1切れ）", kcal: 90, category: "果物" },
  { name: "メロン（1切れ）", kcal: 80, category: "果物" },
  { name: "桃（1個）", kcal: 75, category: "果物" },
  { name: "梨（1個）", kcal: 100, category: "果物" },
  { name: "キウイ（1個）", kcal: 55, category: "果物" },
  { name: "マンゴー（1/2個）", kcal: 100, category: "果物" },
  { name: "パイナップル（1切れ）", kcal: 60, category: "果物" },
  { name: "柿（1個）", kcal: 120, category: "果物" },
  { name: "ブルーベリー（1カップ）", kcal: 80, category: "果物" },
  { name: "さくらんぼ（10粒）", kcal: 45, category: "果物" },

  // ── 野菜・サラダ ─────────────────────────
  { name: "シーザーサラダ", kcal: 250, category: "サラダ" },
  { name: "グリーンサラダ", kcal: 80, category: "サラダ" },
  { name: "コブサラダ", kcal: 300, category: "サラダ" },
  { name: "ニース風サラダ", kcal: 280, category: "サラダ" },
  { name: "ポテトサラダ", kcal: 200, category: "サラダ" },
  { name: "コールスロー", kcal: 150, category: "サラダ" },
  { name: "ほうれん草のソテー", kcal: 80, category: "サラダ" },
  { name: "きんぴらごぼう", kcal: 120, category: "サラダ" },
  { name: "ひじきの煮物", kcal: 100, category: "サラダ" },
  { name: "かぼちゃの煮物", kcal: 130, category: "サラダ" },

  // ── 乳製品・卵 ─────────────────────────
  { name: "ヨーグルト（100g）", kcal: 65, category: "乳製品" },
  { name: "ヨーグルト（無糖・150g）", kcal: 85, category: "乳製品" },
  { name: "ギリシャヨーグルト（100g）", kcal: 70, category: "乳製品" },
  { name: "スライスチーズ（1枚）", kcal: 70, category: "乳製品" },
  { name: "カマンベールチーズ（30g）", kcal: 95, category: "乳製品" },
  { name: "モッツァレラチーズ（50g）", kcal: 125, category: "乳製品" },
  { name: "牛乳（コップ1杯）", kcal: 135, category: "乳製品" },
  { name: "ゆで卵（1個）", kcal: 75, category: "乳製品" },
  { name: "温泉卵（1個）", kcal: 70, category: "乳製品" },
  { name: "バター（1かけ）", kcal: 75, category: "乳製品" },

  // ── 肉・魚 ───────────────────────────────
  { name: "鶏むね肉（100g）", kcal: 105, category: "肉・魚" },
  { name: "鶏もも肉（100g）", kcal: 200, category: "肉・魚" },
  { name: "豚ロース（100g）", kcal: 263, category: "肉・魚" },
  { name: "豚バラ（100g）", kcal: 395, category: "肉・魚" },
  { name: "牛ロース（100g）", kcal: 380, category: "肉・魚" },
  { name: "牛ひき肉（100g）", kcal: 250, category: "肉・魚" },
  { name: "サーモン（100g）", kcal: 170, category: "肉・魚" },
  { name: "マグロ（100g）", kcal: 125, category: "肉・魚" },
  { name: "エビ（100g）", kcal: 80, category: "肉・魚" },
  { name: "ホタテ（100g）", kcal: 70, category: "肉・魚" },
  { name: "イカ（100g）", kcal: 75, category: "肉・魚" },
  { name: "ベーコン（2枚）", kcal: 130, category: "肉・魚" },
  { name: "ウインナー（2本）", kcal: 160, category: "肉・魚" },
  { name: "ハム（2枚）", kcal: 80, category: "肉・魚" },

  // ── 揚げ物・惣菜（個数指定）────────────────
  { name: "からあげ（1個）", kcal: 75, category: "惣菜" },
  { name: "からあげ（3個）", kcal: 225, category: "惣菜" },
  { name: "からあげ（5個）", kcal: 375, category: "惣菜" },
  { name: "からあげ（1個・大）", kcal: 110, category: "惣菜" },
  { name: "鶏天（1個）", kcal: 80, category: "惣菜" },
  { name: "フライドチキン（1本）", kcal: 240, category: "惣菜" },
  { name: "チキンナゲット（1個）", kcal: 50, category: "惣菜" },
  { name: "チキンナゲット（5個）", kcal: 250, category: "惣菜" },
  { name: "コロッケ（1個）", kcal: 170, category: "惣菜" },
  { name: "カニクリームコロッケ（1個）", kcal: 150, category: "惣菜" },
  { name: "メンチカツ（1個）", kcal: 270, category: "惣菜" },
  { name: "とんかつ（1枚）", kcal: 450, category: "惣菜" },
  { name: "ヒレカツ（1枚）", kcal: 350, category: "惣菜" },
  { name: "串カツ（1本）", kcal: 100, category: "惣菜" },
  { name: "エビフライ（1本）", kcal: 90, category: "惣菜" },
  { name: "アジフライ（1枚）", kcal: 160, category: "惣菜" },
  { name: "イカリング（1個）", kcal: 50, category: "惣菜" },
  { name: "ちくわ天（1本）", kcal: 90, category: "惣菜" },
  { name: "天ぷら・えび（1本）", kcal: 70, category: "惣菜" },
  { name: "天ぷら・かぼちゃ（1個）", kcal: 80, category: "惣菜" },
  { name: "天ぷら・なす（1個）", kcal: 60, category: "惣菜" },
  { name: "天ぷら・ちくわ（1本）", kcal: 90, category: "惣菜" },
  { name: "春巻き（1本）", kcal: 110, category: "惣菜" },
  { name: "餃子（1個）", kcal: 40, category: "惣菜" },
  { name: "餃子（5個）", kcal: 200, category: "惣菜" },
  { name: "焼売（1個）", kcal: 35, category: "惣菜" },
  { name: "肉まん（1個）", kcal: 250, category: "惣菜" },
  { name: "あんまん（1個）", kcal: 280, category: "惣菜" },
  { name: "ピザまん（1個）", kcal: 230, category: "惣菜" },
  { name: "ハンバーグ（1個）", kcal: 280, category: "惣菜" },
  { name: "煮込みハンバーグ（1個）", kcal: 350, category: "惣菜" },
  { name: "つくね（1本）", kcal: 90, category: "惣菜" },
  { name: "卵焼き（1切れ）", kcal: 50, category: "惣菜" },
  { name: "だし巻き卵（1切れ）", kcal: 45, category: "惣菜" },
  { name: "ゆで卵（1個）", kcal: 75, category: "惣菜" },
  { name: "目玉焼き（1個）", kcal: 110, category: "惣菜" },
  { name: "ポテトサラダ（小鉢）", kcal: 130, category: "惣菜" },
  { name: "ひじき煮（小鉢）", kcal: 70, category: "惣菜" },
  { name: "きんぴらごぼう（小鉢）", kcal: 80, category: "惣菜" },
  { name: "餃子の王将・餃子（6個）", kcal: 290, category: "惣菜" },

  // ── 焼き鳥（1本）──────────────────────────
  { name: "焼き鳥・もも（1本）", kcal: 95, category: "惣菜" },
  { name: "焼き鳥・ねぎま（1本）", kcal: 80, category: "惣菜" },
  { name: "焼き鳥・つくね（1本）", kcal: 110, category: "惣菜" },
  { name: "焼き鳥・皮（1本）", kcal: 120, category: "惣菜" },
  { name: "焼き鳥・砂肝（1本）", kcal: 40, category: "惣菜" },
  { name: "焼き鳥・レバー（1本）", kcal: 50, category: "惣菜" },
  { name: "焼き鳥・手羽先（1本）", kcal: 110, category: "惣菜" },
  { name: "焼き鳥・ぼんじり（1本）", kcal: 130, category: "惣菜" },

  // ── お菓子（焼き菓子・洋菓子）追加 ──────────
  { name: "ラスク（1枚）", kcal: 50, category: "お菓子" },
  { name: "ラスク（3枚）", kcal: 150, category: "お菓子" },
  { name: "ガトーフェスタハラダ・ラスク（2枚）", kcal: 120, category: "お菓子" },
  { name: "フィナンシェ（1個）", kcal: 130, category: "お菓子" },
  { name: "マドレーヌ（1個）", kcal: 120, category: "お菓子" },
  { name: "マカロン（1個）", kcal: 90, category: "お菓子" },
  { name: "エクレア（1個）", kcal: 200, category: "お菓子" },
  { name: "シュークリーム（1個）", kcal: 180, category: "お菓子" },
  { name: "プチシュー（1個）", kcal: 30, category: "お菓子" },
  { name: "バウムクーヘン（1切れ）", kcal: 250, category: "お菓子" },
  { name: "カステラ（1切れ）", kcal: 160, category: "お菓子" },
  { name: "ワッフル（1個）", kcal: 200, category: "お菓子" },
  { name: "スコーン（1個）", kcal: 230, category: "お菓子" },
  { name: "ビスコッティ（1本）", kcal: 60, category: "お菓子" },
  { name: "クッキー（1枚）", kcal: 50, category: "お菓子" },
  { name: "ビスケット（1枚）", kcal: 45, category: "お菓子" },
  { name: "クラッカー（1枚）", kcal: 20, category: "お菓子" },
  { name: "ウエハース（1枚）", kcal: 35, category: "お菓子" },
  { name: "チュロス（1本）", kcal: 150, category: "お菓子" },
  { name: "ドーナツ（1個）", kcal: 230, category: "お菓子" },
  { name: "オールドファッション（1個）", kcal: 290, category: "お菓子" },
  { name: "ポンデリング（1個）", kcal: 220, category: "お菓子" },
  { name: "チョコファッション（1個）", kcal: 330, category: "お菓子" },
  { name: "プリン（1個）", kcal: 130, category: "お菓子" },
  { name: "プリンアラモード", kcal: 280, category: "お菓子" },
  { name: "ゼリー（1個）", kcal: 70, category: "お菓子" },
  { name: "杏仁豆腐", kcal: 130, category: "お菓子" },
  { name: "パンナコッタ", kcal: 180, category: "お菓子" },
  { name: "ティラミス（1個）", kcal: 250, category: "お菓子" },
  { name: "モンブラン（1個）", kcal: 340, category: "お菓子" },
  { name: "チーズケーキ（1切れ）", kcal: 300, category: "お菓子" },
  { name: "ガトーショコラ（1切れ）", kcal: 320, category: "お菓子" },
  { name: "ショートケーキ（1切れ）", kcal: 340, category: "お菓子" },
  { name: "ロールケーキ（1切れ）", kcal: 200, category: "お菓子" },
  { name: "アップルパイ（1切れ）", kcal: 300, category: "お菓子" },
  { name: "クレープ（1個）", kcal: 280, category: "お菓子" },
  { name: "パフェ", kcal: 450, category: "お菓子" },

  // ── お菓子（和菓子）追加 ──────────────────
  { name: "どら焼き（1個）", kcal: 240, category: "お菓子" },
  { name: "たい焼き（1個）", kcal: 200, category: "お菓子" },
  { name: "大福（1個）", kcal: 170, category: "お菓子" },
  { name: "いちご大福（1個）", kcal: 160, category: "お菓子" },
  { name: "豆大福（1個）", kcal: 180, category: "お菓子" },
  { name: "みたらし団子（1本）", kcal: 120, category: "お菓子" },
  { name: "あんこ団子（1本）", kcal: 130, category: "お菓子" },
  { name: "三色団子（1本）", kcal: 120, category: "お菓子" },
  { name: "おはぎ（1個）", kcal: 180, category: "お菓子" },
  { name: "まんじゅう（1個）", kcal: 140, category: "お菓子" },
  { name: "もみじ饅頭（1個）", kcal: 100, category: "お菓子" },
  { name: "かりんとう饅頭（1個）", kcal: 110, category: "お菓子" },
  { name: "羊羹（1切れ）", kcal: 150, category: "お菓子" },
  { name: "水羊羹（1個）", kcal: 110, category: "お菓子" },
  { name: "わらび餅（1人前）", kcal: 160, category: "お菓子" },
  { name: "くずもち（1人前）", kcal: 140, category: "お菓子" },
  { name: "あんみつ", kcal: 220, category: "お菓子" },
  { name: "白玉ぜんざい", kcal: 280, category: "お菓子" },
  { name: "たいやき（クリーム）", kcal: 210, category: "お菓子" },
  { name: "今川焼き（1個）", kcal: 200, category: "お菓子" },
  { name: "せんべい（1枚）", kcal: 60, category: "お菓子" },
  { name: "ぬれせんべい（1枚）", kcal: 50, category: "お菓子" },
  { name: "おかき（5個）", kcal: 100, category: "お菓子" },
  { name: "あられ（一掴み）", kcal: 90, category: "お菓子" },
  { name: "かりんとう（10本）", kcal: 130, category: "お菓子" },
  { name: "芋けんぴ（一掴み）", kcal: 150, category: "お菓子" },
  { name: "大学芋（小鉢）", kcal: 200, category: "お菓子" },

  // ── お菓子（駄菓子・スナック・チョコ）追加 ──
  { name: "ポップコーン（1袋）", kcal: 300, category: "お菓子" },
  { name: "ポップコーン（カップ）", kcal: 150, category: "お菓子" },
  { name: "チョコレート（1かけ）", kcal: 30, category: "お菓子" },
  { name: "チョコレート（板半分）", kcal: 140, category: "お菓子" },
  { name: "ビターチョコ（1かけ）", kcal: 28, category: "お菓子" },
  { name: "生チョコ（1個）", kcal: 50, category: "お菓子" },
  { name: "トリュフチョコ（1個）", kcal: 60, category: "お菓子" },
  { name: "キャラメル（1個）", kcal: 20, category: "お菓子" },
  { name: "キャンディ・飴（1個）", kcal: 15, category: "お菓子" },
  { name: "のど飴（1個）", kcal: 13, category: "お菓子" },
  { name: "ラムネ菓子（1個）", kcal: 5, category: "お菓子" },
  { name: "グミ（1袋）", kcal: 180, category: "お菓子" },
  { name: "グミ（5粒）", kcal: 30, category: "お菓子" },
  { name: "マシュマロ（1個）", kcal: 15, category: "お菓子" },
  { name: "ゼリービーンズ（10粒）", kcal: 40, category: "お菓子" },
  { name: "チョコボール（1箱）", kcal: 130, category: "お菓子" },
  { name: "ポッキー（1袋）", kcal: 180, category: "お菓子" },
  { name: "ポッキー（5本）", kcal: 80, category: "お菓子" },
  { name: "プリッツ（1袋）", kcal: 150, category: "お菓子" },
  { name: "コアラのマーチ（1箱）", kcal: 250, category: "お菓子" },
  { name: "きのこの山（1箱）", kcal: 420, category: "お菓子" },
  { name: "たけのこの里（1箱）", kcal: 380, category: "お菓子" },
  { name: "ハイチュウ（1個）", kcal: 20, category: "お菓子" },
  { name: "うまい棒（1本）", kcal: 40, category: "お菓子" },
  { name: "ベビースターラーメン（1袋）", kcal: 290, category: "お菓子" },
  { name: "じゃがりこ（1カップ）", kcal: 300, category: "お菓子" },
  { name: "ポテトチップス（小袋）", kcal: 170, category: "お菓子" },
  { name: "プリングルズ（1筒）", kcal: 800, category: "お菓子" },
  { name: "チートス（1袋）", kcal: 280, category: "お菓子" },
  { name: "かっぱえびせん（1袋）", kcal: 260, category: "お菓子" },
  { name: "柿の種（1袋）", kcal: 160, category: "お菓子" },
  { name: "ミックスナッツ（一掴み）", kcal: 180, category: "お菓子" },
  { name: "アーモンド（10粒）", kcal: 60, category: "お菓子" },
  { name: "ドライフルーツ（一掴み）", kcal: 100, category: "お菓子" },
  { name: "甘栗（1袋）", kcal: 150, category: "お菓子" },

  // ── アイス ────────────────────────────────
  { name: "ハーゲンダッツ（1個）", kcal: 250, category: "お菓子" },
  { name: "ソフトクリーム", kcal: 220, category: "お菓子" },
  { name: "アイスクリーム（1個）", kcal: 180, category: "お菓子" },
  { name: "かき氷（シロップ）", kcal: 120, category: "お菓子" },
  { name: "アイスモナカ（1個）", kcal: 230, category: "お菓子" },
  { name: "アイスバー（1本）", kcal: 110, category: "お菓子" },
  { name: "ガリガリ君（1本）", kcal: 70, category: "お菓子" },
  { name: "雪見だいふく（2個）", kcal: 170, category: "お菓子" },
  { name: "ピノ（1箱6粒）", kcal: 190, category: "お菓子" },
  { name: "パピコ（1本）", kcal: 85, category: "お菓子" },

  // ── マクドナルド（追加）──────────────────
  { name: "ダブルチーズバーガー", kcal: 457, category: "ファストフード" },
  { name: "ハンバーガー（マクドナルド）", kcal: 256, category: "ファストフード" },
  { name: "えびフィレオ", kcal: 395, category: "ファストフード" },
  { name: "チキンフィレオ", kcal: 465, category: "ファストフード" },
  { name: "ベーコンレタスバーガー", kcal: 374, category: "ファストフード" },
  { name: "グラコロ", kcal: 410, category: "ファストフード" },
  { name: "月見バーガー", kcal: 410, category: "ファストフード" },
  { name: "スパイシーチキンマックナゲット（5個）", kcal: 290, category: "ファストフード" },
  { name: "シャカチキ", kcal: 233, category: "ファストフード" },
  { name: "ハッシュポテト", kcal: 146, category: "ファストフード" },
  { name: "マックフルーリー", kcal: 250, category: "ファストフード" },
  { name: "ソフトツイスト", kcal: 145, category: "ファストフード" },
  { name: "プレミアムローストコーヒー（M）", kcal: 12, category: "ファストフード" },
  { name: "コカコーラ（M・マクド）", kcal: 140, category: "ファストフード" },
  { name: "ビッグマックセット", kcal: 1075, category: "ファストフード" },

  // ── モスバーガー（追加）──────────────────
  { name: "モスチーズバーガー", kcal: 473, category: "ファストフード" },
  { name: "スパイシーモスバーガー", kcal: 437, category: "ファストフード" },
  { name: "モス フィッシュバーガー", kcal: 360, category: "ファストフード" },
  { name: "ロースカツバーガー（MOS）", kcal: 460, category: "ファストフード" },
  { name: "モスチキン", kcal: 230, category: "ファストフード" },
  { name: "オニオンフライ（MOS）", kcal: 260, category: "ファストフード" },
  { name: "モスポテト", kcal: 220, category: "ファストフード" },

  // ── ロッテリア ────────────────────────────
  { name: "絶品チーズバーガー", kcal: 393, category: "ファストフード" },
  { name: "エビバーガー（ロッテリア）", kcal: 423, category: "ファストフード" },
  { name: "リブサンド（ビーフ）", kcal: 500, category: "ファストフード" },
  { name: "ロッテリアポテト（M）", kcal: 290, category: "ファストフード" },
  { name: "ぷるぷるホットケーキ", kcal: 380, category: "ファストフード" },

  // ── バーガーキング ────────────────────────
  { name: "ワッパー", kcal: 640, category: "ファストフード" },
  { name: "ワッパーチーズ", kcal: 710, category: "ファストフード" },
  { name: "ダブルワッパー", kcal: 900, category: "ファストフード" },
  { name: "ワッパージュニア", kcal: 380, category: "ファストフード" },
  { name: "クリスピーチキン（BK）", kcal: 280, category: "ファストフード" },
  { name: "オニオンリング（BK・M）", kcal: 320, category: "ファストフード" },

  // ── ケンタッキー（追加）──────────────────
  { name: "ケンタッキー 骨なしケンタッキー", kcal: 204, category: "ファストフード" },
  { name: "ケンタッキー チキンフィレサンド", kcal: 415, category: "ファストフード" },
  { name: "ケンタッキー 和風チキンカツサンド", kcal: 460, category: "ファストフード" },
  { name: "ケンタッキー ビスケット（1個）", kcal: 200, category: "ファストフード" },
  { name: "ケンタッキー カーネルクリスピー", kcal: 130, category: "ファストフード" },
  { name: "ケンタッキー ナゲット（5個）", kcal: 230, category: "ファストフード" },
  { name: "ケンタッキー コールスロー（S）", kcal: 92, category: "ファストフード" },

  // ── その他チェーン ────────────────────────
  { name: "ファーストキッチン ベーコンエッグバーガー", kcal: 430, category: "ファストフード" },
  { name: "フレッシュネス クラシックバーガー", kcal: 470, category: "ファストフード" },
  { name: "ドムドム ハンバーガー", kcal: 350, category: "ファストフード" },
  { name: "サブウェイ（えびアボカド）", kcal: 330, category: "ファストフード" },
  { name: "サブウェイ（ローストチキン）", kcal: 320, category: "ファストフード" },
  { name: "サブウェイ（てりやきチキン）", kcal: 360, category: "ファストフード" },
  { name: "クアアイナ アボカドバーガー", kcal: 700, category: "ファストフード" },

  // ── 牛丼・定食チェーン（追加）────────────
  { name: "すき家 チーズ牛丼（並）", kcal: 822, category: "ファストフード" },
  { name: "すき家 牛丼（大盛）", kcal: 875, category: "ファストフード" },
  { name: "吉野家 チーズ牛丼（並）", kcal: 780, category: "ファストフード" },
  { name: "松屋 プレミアム牛めし（並）", kcal: 645, category: "ファストフード" },
  { name: "松屋 豚丼（並）", kcal: 690, category: "ファストフード" },
  { name: "なか卯 親子丼（並）", kcal: 670, category: "ファストフード" },
  { name: "天丼てんや 天丼", kcal: 700, category: "ファストフード" },
  { name: "丸亀製麺 かけうどん（並）", kcal: 290, category: "ファストフード" },
  { name: "丸亀製麺 釜玉うどん（並）", kcal: 540, category: "ファストフード" },
  { name: "はなまるうどん かけ（中）", kcal: 320, category: "ファストフード" },
  { name: "CoCo壱番屋 ポークカレー", kcal: 730, category: "ファストフード" },
  { name: "CoCo壱番屋 カツカレー", kcal: 1050, category: "ファストフード" },

  // ── ラーメン（追加）────────────────────────
  { name: "魚介豚骨ラーメン", kcal: 700, category: "和食" },
  { name: "魚介つけ麺（並）", kcal: 800, category: "和食" },
  { name: "魚介つけ麺（大盛）", kcal: 1000, category: "和食" },
  { name: "鶏白湯ラーメン", kcal: 580, category: "和食" },
  { name: "鶏白湯つけ麺", kcal: 750, category: "和食" },
  { name: "四川ラーメン（激辛）", kcal: 650, category: "中華" },
  { name: "麻婆ラーメン", kcal: 720, category: "中華" },
  { name: "汁なし担々麺", kcal: 680, category: "中華" },
  { name: "黒ごま担々麺", kcal: 720, category: "中華" },
  { name: "家系ラーメン", kcal: 850, category: "和食" },
  { name: "二郎系ラーメン（小）", kcal: 1100, category: "和食" },
  { name: "二郎系ラーメン（並）", kcal: 1500, category: "和食" },
  { name: "二郎系ラーメン（大）", kcal: 1900, category: "和食" },
  { name: "ちゃんぽん", kcal: 660, category: "和食" },
  { name: "皿うどん（揚げ）", kcal: 700, category: "中華" },
  { name: "油そば", kcal: 720, category: "和食" },
  { name: "まぜそば（汁なし）", kcal: 730, category: "和食" },
  { name: "カレーラーメン", kcal: 620, category: "和食" },
  { name: "味噌バターコーンラーメン", kcal: 680, category: "和食" },
  { name: "とんこつ醤油ラーメン", kcal: 620, category: "和食" },
  { name: "ピリ辛味噌ラーメン", kcal: 600, category: "和食" },
  { name: "冷やしラーメン", kcal: 480, category: "和食" },
  { name: "冷やし中華", kcal: 500, category: "中華" },
  { name: "野菜ラーメン（タンメン）", kcal: 480, category: "中華" },
  { name: "海老ワンタン麺", kcal: 540, category: "中華" },
  { name: "肉ワンタン麺", kcal: 560, category: "中華" },
  { name: "ベジタブルラーメン", kcal: 450, category: "和食" },

  // ── うどん（追加）─────────────────────────
  { name: "釜揚げうどん", kcal: 380, category: "和食" },
  { name: "ぶっかけうどん", kcal: 360, category: "和食" },
  { name: "ぶっかけうどん（冷）", kcal: 350, category: "和食" },
  { name: "きつねうどん", kcal: 420, category: "和食" },
  { name: "たぬきうどん", kcal: 410, category: "和食" },
  { name: "月見うどん", kcal: 380, category: "和食" },
  { name: "わかめうどん", kcal: 330, category: "和食" },
  { name: "山菜うどん", kcal: 340, category: "和食" },
  { name: "とろろうどん", kcal: 380, category: "和食" },
  { name: "梅おろしうどん", kcal: 320, category: "和食" },
  { name: "鍋焼きうどん", kcal: 560, category: "和食" },
  { name: "海老天うどん", kcal: 490, category: "和食" },
  { name: "ごぼう天うどん", kcal: 440, category: "和食" },
  { name: "ちくわ天うどん", kcal: 420, category: "和食" },
  { name: "かしわ天うどん", kcal: 470, category: "和食" },
  { name: "鶏南蛮うどん", kcal: 500, category: "和食" },
  { name: "カレーうどん", kcal: 520, category: "和食" },
  { name: "焼きうどん", kcal: 480, category: "和食" },
  { name: "味噌煮込みうどん", kcal: 600, category: "和食" },
  { name: "サラダうどん", kcal: 380, category: "和食" },
  { name: "明太子うどん", kcal: 460, category: "和食" },
  { name: "釜玉うどん", kcal: 450, category: "和食" },
  { name: "ぶっかけうどん（特盛）", kcal: 540, category: "和食" },

  // ── そば（追加）───────────────────────────
  { name: "かけそば", kcal: 280, category: "和食" },
  { name: "月見そば", kcal: 360, category: "和食" },
  { name: "たぬきそば", kcal: 380, category: "和食" },
  { name: "きつねそば", kcal: 400, category: "和食" },
  { name: "わかめそば", kcal: 310, category: "和食" },
  { name: "山菜そば", kcal: 340, category: "和食" },
  { name: "とろろそば", kcal: 380, category: "和食" },
  { name: "おろしそば", kcal: 320, category: "和食" },
  { name: "鴨南蛮そば", kcal: 520, category: "和食" },
  { name: "海老天そば", kcal: 460, category: "和食" },
  { name: "天ぷらそば（盛り合わせ）", kcal: 580, category: "和食" },
  { name: "にしんそば", kcal: 480, category: "和食" },
  { name: "カレーそば", kcal: 500, category: "和食" },
  { name: "鍋焼きそば", kcal: 550, category: "和食" },
  { name: "冷やしたぬきそば", kcal: 380, category: "和食" },
  { name: "ざるそば（大盛）", kcal: 470, category: "和食" },
  { name: "天ざるそば", kcal: 580, category: "和食" },
  { name: "せいろそば", kcal: 320, category: "和食" },
  { name: "出雲そば（割子3段）", kcal: 420, category: "和食" },
  { name: "わんこそば（10杯）", kcal: 200, category: "和食" },

  // ── パン屋（追加）─────────────────────────
  { name: "塩パン", kcal: 200, category: "パン" },
  { name: "明太フランス", kcal: 380, category: "パン" },
  { name: "ガーリックトースト（1切れ）", kcal: 180, category: "パン" },
  { name: "ピザトースト（1枚）", kcal: 320, category: "パン" },
  { name: "ハニートースト", kcal: 380, category: "パン" },
  { name: "フレンチトースト（1枚）", kcal: 340, category: "パン" },
  { name: "マリトッツォ", kcal: 320, category: "パン" },
  { name: "フルーツサンド", kcal: 380, category: "パン" },
  { name: "カツサンド", kcal: 520, category: "パン" },
  { name: "卵サンド（パン屋）", kcal: 380, category: "パン" },
  { name: "BLT サンド", kcal: 420, category: "パン" },
  { name: "クロワッサンサンド", kcal: 360, category: "パン" },
  { name: "バゲットサンド", kcal: 400, category: "パン" },
  { name: "ベーコンエピ", kcal: 340, category: "パン" },
  { name: "クロックムッシュ", kcal: 420, category: "パン" },
  { name: "パン・オ・ショコラ", kcal: 330, category: "パン" },
  { name: "ブリオッシュ（1個）", kcal: 290, category: "パン" },
  { name: "カンパーニュ（1切れ）", kcal: 130, category: "パン" },
  { name: "ライ麦パン（1切れ）", kcal: 140, category: "パン" },
  { name: "全粒粉パン（1切れ）", kcal: 150, category: "パン" },
  { name: "黒糖パン（1個）", kcal: 250, category: "パン" },
  { name: "レーズンパン（1個）", kcal: 260, category: "パン" },
  { name: "ぶどうパン（1個）", kcal: 240, category: "パン" },
  { name: "抹茶あんぱん", kcal: 310, category: "パン" },
  { name: "桜あんぱん", kcal: 300, category: "パン" },
  { name: "うぐいすパン", kcal: 290, category: "パン" },
  { name: "ハム＆チーズパン", kcal: 320, category: "パン" },
  { name: "ベーコンチーズパン", kcal: 360, category: "パン" },
  { name: "ソーセージパン", kcal: 330, category: "パン" },
  { name: "焼きカレーパン", kcal: 350, category: "パン" },
  { name: "ピザパン", kcal: 340, category: "パン" },
  { name: "コーンマヨパン", kcal: 320, category: "パン" },
  { name: "ツナマヨパン", kcal: 340, category: "パン" },
  { name: "卵コッペパン", kcal: 360, category: "パン" },
  { name: "ピーナッツコッペパン", kcal: 380, category: "パン" },
  { name: "ジャムコッペパン", kcal: 320, category: "パン" },
  { name: "ホイップあんぱん", kcal: 350, category: "パン" },
  { name: "白あんぱん", kcal: 290, category: "パン" },
  { name: "アップルパイ（パン屋）", kcal: 380, category: "パン" },
  { name: "カスタードクリームパン", kcal: 310, category: "パン" },
  { name: "抹茶クリームパン", kcal: 320, category: "パン" },

  // ── 流行りの飲み物・タピオカ（追加）─────────
  { name: "タピオカミルクティー（M）", kcal: 350, category: "飲み物" },
  { name: "タピオカミルクティー（L）", kcal: 450, category: "飲み物" },
  { name: "タピオカ抹茶ラテ", kcal: 380, category: "飲み物" },
  { name: "タピオカほうじ茶ラテ", kcal: 360, category: "飲み物" },
  { name: "黒糖タピオカミルク", kcal: 480, category: "飲み物" },
  { name: "黒糖タピオカ抹茶ラテ", kcal: 460, category: "飲み物" },
  { name: "タピオカマンゴーミルク", kcal: 400, category: "飲み物" },
  { name: "タピオカいちごミルク", kcal: 390, category: "飲み物" },
  { name: "タピオカフルーツティー", kcal: 320, category: "飲み物" },
  { name: "チーズティー", kcal: 280, category: "飲み物" },
  { name: "イチゴラテ", kcal: 280, category: "飲み物" },
  { name: "苺ミルク", kcal: 250, category: "飲み物" },
  { name: "バナナジュース（M）", kcal: 320, category: "飲み物" },
  { name: "バナナミルク", kcal: 280, category: "飲み物" },
  { name: "スムージー（フルーツ）", kcal: 250, category: "飲み物" },
  { name: "グリーンスムージー", kcal: 180, category: "飲み物" },
  { name: "プロテインスムージー", kcal: 280, category: "飲み物" },
  { name: "アサイースムージー", kcal: 260, category: "飲み物" },
  { name: "アサイーボウル（ドリンク）", kcal: 320, category: "飲み物" },
  { name: "抹茶フラペチーノ", kcal: 380, category: "飲み物" },
  { name: "ほうじ茶フラペチーノ", kcal: 320, category: "飲み物" },
  { name: "いちごフラペチーノ", kcal: 360, category: "飲み物" },
  { name: "チャイラテ（ホット）", kcal: 220, category: "飲み物" },
  { name: "ロイヤルミルクティー", kcal: 250, category: "飲み物" },
  { name: "ダーティーラテ", kcal: 200, category: "飲み物" },
  { name: "アーモンドラテ", kcal: 180, category: "飲み物" },
  { name: "オーツミルクラテ", kcal: 170, category: "飲み物" },
  { name: "ソイラテ", kcal: 180, category: "飲み物" },
  { name: "ココアラテ", kcal: 240, category: "飲み物" },
  { name: "ホットチョコレート", kcal: 320, category: "飲み物" },
  { name: "レモネード", kcal: 150, category: "飲み物" },
  { name: "ピンクレモネード", kcal: 200, category: "飲み物" },
  { name: "ホットレモネード（ハチミツ）", kcal: 130, category: "飲み物" },
  { name: "ジンジャーエール（350ml）", kcal: 140, category: "飲み物" },
  { name: "クラフトコーラ", kcal: 160, category: "飲み物" },
  { name: "フルーツビネガードリンク", kcal: 100, category: "飲み物" },
  { name: "コンブチャ（200ml）", kcal: 40, category: "飲み物" },
  { name: "スパークリングコーヒー", kcal: 80, category: "飲み物" },
  { name: "ノンアルコールビール（350ml）", kcal: 50, category: "飲み物" },
  { name: "ノンアルコールチューハイ（350ml）", kcal: 30, category: "飲み物" },
  { name: "カクテル モヒート", kcal: 160, category: "飲み物" },
  { name: "カクテル モスコミュール", kcal: 180, category: "飲み物" },
  { name: "カクテル ジントニック", kcal: 170, category: "飲み物" },
  { name: "カクテル カシスオレンジ", kcal: 170, category: "飲み物" },
  { name: "梅酒ロック", kcal: 110, category: "飲み物" },
  { name: "梅酒ソーダ", kcal: 100, category: "飲み物" },
];

export function searchFoods(query: string): FoodItem[] {
  if (!query.trim()) return [];
  const q = query.trim();
  // 前方一致を優先、次に部分一致
  const exact = FOOD_DATABASE.filter(f => f.name.startsWith(q));
  const partial = FOOD_DATABASE.filter(f => !f.name.startsWith(q) && f.name.includes(q));
  return [...exact, ...partial].slice(0, 25);
}
