export interface FoodItem {
  name: string;
  kcal: number;
  category: string;
  /** カテゴリ内の小見出し（丼もの・寿司など）。無いカテゴリはフラット表示 */
  sub?: string;
}

// 食品カテゴリ（「カテゴリから選ぶ」の表示順とアイコン）
export const FOOD_CATEGORIES: { key: string; emoji: string }[] = [
  { key: "和食",          emoji: "🍚" },
  { key: "洋食",          emoji: "🍝" },
  { key: "中華",          emoji: "🥟" },
  { key: "韓国・エスニック", emoji: "🌶️" },
  { key: "ファストフード",  emoji: "🍔" },
  { key: "コンビニ",      emoji: "🏪" },
  { key: "パン",          emoji: "🥐" },
  { key: "惣菜",          emoji: "🍱" },
  { key: "スーパー惣菜",   emoji: "🛒" },
  { key: "サラダ・野菜",   emoji: "🥗" },
  { key: "肉・魚",        emoji: "🍖" },
  { key: "乳製品・卵",     emoji: "🧀" },
  { key: "果物",          emoji: "🍓" },
  { key: "お菓子",        emoji: "🍰" },
  { key: "飲み物",        emoji: "🥤" },
];

export const FOOD_DATABASE: FoodItem[] = [
  // ══ 和食 ════════════════════════════════════
  // 定食・主菜
  { name: "焼き魚定食", kcal: 500, category: "和食", sub: "定食・主菜" },
  { name: "鮭の塩焼き定食", kcal: 520, category: "和食", sub: "定食・主菜" },
  { name: "さばの味噌煮定食", kcal: 600, category: "和食", sub: "定食・主菜" },
  { name: "さばの塩焼き定食", kcal: 560, category: "和食", sub: "定食・主菜" },
  { name: "ぶりの照り焼き定食", kcal: 650, category: "和食", sub: "定食・主菜" },
  { name: "刺身定食", kcal: 500, category: "和食", sub: "定食・主菜" },
  { name: "肉じゃが定食", kcal: 550, category: "和食", sub: "定食・主菜" },
  { name: "唐揚げ定食", kcal: 750, category: "和食", sub: "定食・主菜" },
  { name: "天ぷら定食", kcal: 800, category: "和食", sub: "定食・主菜" },
  { name: "豚汁定食", kcal: 600, category: "和食", sub: "定食・主菜" },
  { name: "豚の生姜焼き定食", kcal: 700, category: "和食", sub: "定食・主菜" },
  { name: "鶏の照り焼き定食", kcal: 680, category: "和食", sub: "定食・主菜" },
  { name: "チキン南蛮定食", kcal: 700, category: "和食", sub: "定食・主菜" },
  { name: "回鍋肉定食", kcal: 720, category: "和食", sub: "定食・主菜" },
  { name: "麻婆豆腐定食", kcal: 650, category: "和食", sub: "定食・主菜" },
  { name: "とんかつ定食", kcal: 900, category: "和食", sub: "定食・主菜" },
  { name: "ヒレカツ定食", kcal: 800, category: "和食", sub: "定食・主菜" },
  { name: "アジフライ定食", kcal: 650, category: "和食", sub: "定食・主菜" },
  { name: "煮魚定食", kcal: 580, category: "和食", sub: "定食・主菜" },
  { name: "焼肉定食", kcal: 800, category: "和食", sub: "定食・主菜" },
  { name: "すき焼き定食", kcal: 850, category: "和食", sub: "定食・主菜" },
  { name: "しゃぶしゃぶ定食", kcal: 700, category: "和食", sub: "定食・主菜" },
  // 丼もの
  { name: "親子丼", kcal: 650, category: "和食", sub: "丼もの" },
  { name: "カツ丼", kcal: 900, category: "和食", sub: "丼もの" },
  { name: "牛丼（並）", kcal: 660, category: "和食", sub: "丼もの" },
  { name: "牛丼（大盛）", kcal: 830, category: "和食", sub: "丼もの" },
  { name: "牛丼（特盛）", kcal: 980, category: "和食", sub: "丼もの" },
  { name: "天丼", kcal: 850, category: "和食", sub: "丼もの" },
  { name: "海鮮丼", kcal: 600, category: "和食", sub: "丼もの" },
  { name: "うな丼", kcal: 780, category: "和食", sub: "丼もの" },
  { name: "うな重", kcal: 850, category: "和食", sub: "丼もの" },
  { name: "豚丼", kcal: 720, category: "和食", sub: "丼もの" },
  { name: "鉄火丼", kcal: 500, category: "和食", sub: "丼もの" },
  { name: "ネギトロ丼", kcal: 580, category: "和食", sub: "丼もの" },
  { name: "いくら丼", kcal: 600, category: "和食", sub: "丼もの" },
  { name: "三色丼", kcal: 620, category: "和食", sub: "丼もの" },
  { name: "そぼろ丼", kcal: 580, category: "和食", sub: "丼もの" },
  // 寿司
  { name: "寿司（並・10貫）", kcal: 500, category: "和食", sub: "寿司" },
  { name: "寿司（上・10貫）", kcal: 600, category: "和食", sub: "寿司" },
  { name: "手巻き寿司", kcal: 400, category: "和食", sub: "寿司" },
  { name: "ちらし寿司", kcal: 550, category: "和食", sub: "寿司" },
  { name: "稲荷寿司（2個）", kcal: 200, category: "和食", sub: "寿司" },
  { name: "細巻き（1本）", kcal: 200, category: "和食", sub: "寿司" },
  { name: "太巻き（1本）", kcal: 450, category: "和食", sub: "寿司" },
  { name: "恵方巻き（1本）", kcal: 520, category: "和食", sub: "寿司" },
  // うどん
  { name: "かけうどん", kcal: 300, category: "和食", sub: "うどん" },
  { name: "きつねうどん", kcal: 420, category: "和食", sub: "うどん" },
  { name: "たぬきうどん", kcal: 410, category: "和食", sub: "うどん" },
  { name: "月見うどん", kcal: 380, category: "和食", sub: "うどん" },
  { name: "肉うどん", kcal: 450, category: "和食", sub: "うどん" },
  { name: "カレーうどん", kcal: 520, category: "和食", sub: "うどん" },
  { name: "鍋焼きうどん", kcal: 560, category: "和食", sub: "うどん" },
  { name: "釜玉うどん", kcal: 450, category: "和食", sub: "うどん" },
  { name: "ぶっかけうどん", kcal: 360, category: "和食", sub: "うどん" },
  { name: "焼きうどん", kcal: 480, category: "和食", sub: "うどん" },
  { name: "ざるうどん", kcal: 280, category: "和食", sub: "うどん" },
  { name: "天ぷらうどん", kcal: 490, category: "和食", sub: "うどん" },
  { name: "味噌煮込みうどん", kcal: 600, category: "和食", sub: "うどん" },
  { name: "とろろうどん", kcal: 380, category: "和食", sub: "うどん" },
  { name: "明太子うどん", kcal: 460, category: "和食", sub: "うどん" },
  // そば
  { name: "ざるそば", kcal: 340, category: "和食", sub: "そば" },
  { name: "かけそば", kcal: 280, category: "和食", sub: "そば" },
  { name: "月見そば", kcal: 360, category: "和食", sub: "そば" },
  { name: "たぬきそば", kcal: 380, category: "和食", sub: "そば" },
  { name: "きつねそば", kcal: 400, category: "和食", sub: "そば" },
  { name: "天ぷらそば", kcal: 460, category: "和食", sub: "そば" },
  { name: "天ざるそば", kcal: 580, category: "和食", sub: "そば" },
  { name: "鴨南蛮そば", kcal: 520, category: "和食", sub: "そば" },
  { name: "とろろそば", kcal: 380, category: "和食", sub: "そば" },
  { name: "肉そば", kcal: 430, category: "和食", sub: "そば" },
  { name: "山菜そば", kcal: 340, category: "和食", sub: "そば" },
  { name: "おろしそば", kcal: 320, category: "和食", sub: "そば" },
  // ラーメン
  { name: "醤油ラーメン", kcal: 450, category: "和食", sub: "ラーメン" },
  { name: "味噌ラーメン", kcal: 550, category: "和食", sub: "ラーメン" },
  { name: "塩ラーメン", kcal: 420, category: "和食", sub: "ラーメン" },
  { name: "豚骨ラーメン", kcal: 580, category: "和食", sub: "ラーメン" },
  { name: "チャーシュー麺", kcal: 620, category: "和食", sub: "ラーメン" },
  { name: "つけ麺", kcal: 700, category: "和食", sub: "ラーメン" },
  { name: "魚介つけ麺", kcal: 800, category: "和食", sub: "ラーメン" },
  { name: "家系ラーメン", kcal: 850, category: "和食", sub: "ラーメン" },
  { name: "二郎系ラーメン（並）", kcal: 1500, category: "和食", sub: "ラーメン" },
  { name: "味噌バターコーンラーメン", kcal: 680, category: "和食", sub: "ラーメン" },
  { name: "鶏白湯ラーメン", kcal: 580, category: "和食", sub: "ラーメン" },
  { name: "油そば", kcal: 720, category: "和食", sub: "ラーメン" },
  { name: "ちゃんぽん", kcal: 660, category: "和食", sub: "ラーメン" },
  { name: "ワンタン麺", kcal: 540, category: "和食", sub: "ラーメン" },
  { name: "野菜タンメン", kcal: 480, category: "和食", sub: "ラーメン" },
  // 粉もの・鍋・その他
  { name: "焼きそば", kcal: 500, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "お好み焼き", kcal: 560, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "広島風お好み焼き", kcal: 650, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "たこ焼き（8個）", kcal: 300, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "もんじゃ焼き", kcal: 400, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おでん（5品）", kcal: 300, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "茶碗蒸し", kcal: 80, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "味噌汁", kcal: 40, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "豚汁", kcal: 150, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "けんちん汁", kcal: 120, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "冷奴", kcal: 80, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "湯豆腐", kcal: 150, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "納豆ご飯", kcal: 330, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "卵かけご飯", kcal: 310, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "白米（1杯）", kcal: 250, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "白米（大盛）", kcal: 390, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "玄米ご飯（1杯）", kcal: 230, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おかゆ", kcal: 150, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "雑炊", kcal: 200, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "焼きおにぎり", kcal: 190, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おにぎり（梅）", kcal: 180, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おにぎり（鮭）", kcal: 190, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おにぎり（ツナマヨ）", kcal: 210, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おにぎり（昆布）", kcal: 175, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おにぎり（明太子）", kcal: 185, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おにぎり（おかか）", kcal: 180, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "おにぎり（高菜）", kcal: 180, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "すき焼き", kcal: 600, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "しゃぶしゃぶ", kcal: 500, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "寄せ鍋", kcal: 400, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "水炊き", kcal: 450, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "もつ鍋", kcal: 600, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "キムチ鍋", kcal: 500, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "ちゃんこ鍋", kcal: 550, category: "和食", sub: "粉もの・鍋・その他" },
  { name: "焼き鳥盛り合わせ（5本）", kcal: 350, category: "和食", sub: "粉もの・鍋・その他" },

  // ══ 洋食 ════════════════════════════════════
  { name: "ハンバーグ定食", kcal: 850, category: "洋食" },
  { name: "デミグラスハンバーグ", kcal: 500, category: "洋食" },
  { name: "煮込みハンバーグ", kcal: 400, category: "洋食" },
  { name: "チーズハンバーグ", kcal: 520, category: "洋食" },
  { name: "ロコモコ", kcal: 750, category: "洋食" },
  { name: "チキンソテー定食", kcal: 700, category: "洋食" },
  { name: "ステーキ（150g）", kcal: 400, category: "洋食" },
  { name: "ステーキ（200g）", kcal: 550, category: "洋食" },
  { name: "サーロインステーキ", kcal: 650, category: "洋食" },
  { name: "ローストビーフ丼", kcal: 650, category: "洋食" },
  { name: "ビーフシチュー定食", kcal: 750, category: "洋食" },
  { name: "クリームシチュー", kcal: 450, category: "洋食" },
  { name: "ポトフ", kcal: 250, category: "洋食" },
  { name: "ロールキャベツ", kcal: 280, category: "洋食" },
  { name: "ビーフストロガノフ", kcal: 600, category: "洋食" },
  { name: "オムライス", kcal: 750, category: "洋食" },
  { name: "ドリア", kcal: 600, category: "洋食" },
  { name: "シーフードドリア", kcal: 650, category: "洋食" },
  { name: "ミートドリア", kcal: 620, category: "洋食" },
  { name: "グラタン", kcal: 550, category: "洋食" },
  { name: "マカロニグラタン", kcal: 520, category: "洋食" },
  { name: "ラザニア", kcal: 450, category: "洋食" },
  { name: "ハヤシライス", kcal: 800, category: "洋食" },
  { name: "カレーライス", kcal: 900, category: "洋食" },
  { name: "カレーライス（大盛）", kcal: 1100, category: "洋食" },
  { name: "カツカレー", kcal: 1050, category: "洋食" },
  { name: "ハンバーグカレー", kcal: 1000, category: "洋食" },
  { name: "ビーフカレー", kcal: 850, category: "洋食" },
  { name: "シーフードカレー", kcal: 800, category: "洋食" },
  { name: "キーマカレー", kcal: 750, category: "洋食" },
  { name: "スープカレー", kcal: 600, category: "洋食" },
  { name: "ナポリタン", kcal: 650, category: "洋食" },
  { name: "ミートソーススパゲッティ", kcal: 700, category: "洋食" },
  { name: "カルボナーラ", kcal: 800, category: "洋食" },
  { name: "ペペロンチーノ", kcal: 600, category: "洋食" },
  { name: "ボロネーゼ", kcal: 700, category: "洋食" },
  { name: "トマトソースパスタ", kcal: 550, category: "洋食" },
  { name: "きのこパスタ", kcal: 560, category: "洋食" },
  { name: "明太子パスタ", kcal: 620, category: "洋食" },
  { name: "たらこパスタ", kcal: 600, category: "洋食" },
  { name: "ジェノベーゼ", kcal: 650, category: "洋食" },
  { name: "ボンゴレ（あさり）", kcal: 580, category: "洋食" },
  { name: "海老クリームパスタ", kcal: 720, category: "洋食" },
  { name: "ピザ（マルゲリータ）", kcal: 700, category: "洋食" },
  { name: "ピザ（クワトロフォルマッジ）", kcal: 850, category: "洋食" },
  { name: "ピザ（テリヤキチキン）", kcal: 800, category: "洋食" },
  { name: "ピザ（ミックス）", kcal: 780, category: "洋食" },
  { name: "ピザ（マリナーラ）", kcal: 600, category: "洋食" },
  { name: "コロッケ定食", kcal: 700, category: "洋食" },
  { name: "エビフライ定食", kcal: 800, category: "洋食" },
  { name: "カニクリームコロッケ定食", kcal: 720, category: "洋食" },
  { name: "ポークソテー", kcal: 550, category: "洋食" },
  { name: "ミネストローネ", kcal: 150, category: "洋食" },
  { name: "クラムチャウダー", kcal: 200, category: "洋食" },
  { name: "コーンスープ", kcal: 140, category: "洋食" },
  { name: "オニオングラタンスープ", kcal: 250, category: "洋食" },
  { name: "ハムエッグ", kcal: 280, category: "洋食" },
  { name: "ベーコンエッグ", kcal: 300, category: "洋食" },
  { name: "スクランブルエッグ", kcal: 200, category: "洋食" },
  { name: "目玉焼き", kcal: 110, category: "洋食" },
  { name: "オムレツ", kcal: 250, category: "洋食" },
  { name: "エッグベネディクト", kcal: 450, category: "洋食" },
  { name: "フレンチトースト", kcal: 380, category: "洋食" },
  { name: "パンケーキ（2枚）", kcal: 420, category: "洋食" },

  // ══ 中華 ════════════════════════════════════
  { name: "焼き餃子（6個）", kcal: 280, category: "中華" },
  { name: "水餃子（6個）", kcal: 200, category: "中華" },
  { name: "揚げ餃子（6個）", kcal: 380, category: "中華" },
  { name: "餃子定食", kcal: 650, category: "中華" },
  { name: "酢豚定食", kcal: 700, category: "中華" },
  { name: "酢豚（単品）", kcal: 280, category: "中華" },
  { name: "チャーハン", kcal: 700, category: "中華" },
  { name: "五目チャーハン", kcal: 680, category: "中華" },
  { name: "高菜チャーハン", kcal: 650, category: "中華" },
  { name: "海老チャーハン", kcal: 700, category: "中華" },
  { name: "あんかけチャーハン", kcal: 720, category: "中華" },
  { name: "八宝菜定食", kcal: 600, category: "中華" },
  { name: "八宝菜（単品）", kcal: 200, category: "中華" },
  { name: "エビチリ定食", kcal: 620, category: "中華" },
  { name: "エビチリ（単品）", kcal: 230, category: "中華" },
  { name: "エビマヨ", kcal: 300, category: "中華" },
  { name: "中華丼", kcal: 680, category: "中華" },
  { name: "天津飯", kcal: 650, category: "中華" },
  { name: "麻婆丼", kcal: 600, category: "中華" },
  { name: "担々麺", kcal: 700, category: "中華" },
  { name: "汁なし担々麺", kcal: 680, category: "中華" },
  { name: "黒ごま担々麺", kcal: 720, category: "中華" },
  { name: "麻婆ラーメン", kcal: 720, category: "中華" },
  { name: "四川ラーメン（激辛）", kcal: 650, category: "中華" },
  { name: "冷やし中華", kcal: 500, category: "中華" },
  { name: "冷麺", kcal: 450, category: "中華" },
  { name: "小籠包（5個）", kcal: 250, category: "中華" },
  { name: "海老蒸し餃子（4個）", kcal: 160, category: "中華" },
  { name: "春巻き（2本）", kcal: 300, category: "中華" },
  { name: "シュウマイ（5個）", kcal: 200, category: "中華" },
  { name: "青椒肉絲", kcal: 350, category: "中華" },
  { name: "青椒肉絲定食", kcal: 680, category: "中華" },
  { name: "回鍋肉", kcal: 310, category: "中華" },
  { name: "麻婆豆腐", kcal: 220, category: "中華" },
  { name: "麻婆茄子", kcal: 250, category: "中華" },
  { name: "油淋鶏", kcal: 350, category: "中華" },
  { name: "よだれ鶏", kcal: 300, category: "中華" },
  { name: "バンバンジー", kcal: 250, category: "中華" },
  { name: "棒棒鶏", kcal: 280, category: "中華" },
  { name: "北京ダック（2枚）", kcal: 120, category: "中華" },
  { name: "中華粥", kcal: 150, category: "中華" },
  { name: "皿うどん（揚げ）", kcal: 700, category: "中華" },
  { name: "あんかけ焼きそば", kcal: 600, category: "中華" },
  { name: "台湾まぜそば", kcal: 750, category: "中華" },

  // ══ 韓国・エスニック ══════════════════════════
  { name: "ビビンバ", kcal: 650, category: "韓国・エスニック" },
  { name: "石焼きビビンバ", kcal: 700, category: "韓国・エスニック" },
  { name: "クッパ", kcal: 450, category: "韓国・エスニック" },
  { name: "韓国冷麺", kcal: 480, category: "韓国・エスニック" },
  { name: "ビビン麺", kcal: 520, category: "韓国・エスニック" },
  { name: "スンドゥブチゲ", kcal: 400, category: "韓国・エスニック" },
  { name: "チゲ鍋", kcal: 500, category: "韓国・エスニック" },
  { name: "サムギョプサル（100g）", kcal: 380, category: "韓国・エスニック" },
  { name: "タッカルビ", kcal: 550, category: "韓国・エスニック" },
  { name: "チーズタッカルビ", kcal: 650, category: "韓国・エスニック" },
  { name: "ヤンニョムチキン（3個）", kcal: 350, category: "韓国・エスニック" },
  { name: "キンパ（1本）", kcal: 400, category: "韓国・エスニック" },
  { name: "トッポギ", kcal: 350, category: "韓国・エスニック" },
  { name: "チヂミ", kcal: 400, category: "韓国・エスニック" },
  { name: "ナムル（小鉢）", kcal: 80, category: "韓国・エスニック" },
  { name: "キムチ（小鉢）", kcal: 30, category: "韓国・エスニック" },
  { name: "ガパオライス", kcal: 580, category: "韓国・エスニック" },
  { name: "グリーンカレー", kcal: 320, category: "韓国・エスニック" },
  { name: "レッドカレー", kcal: 330, category: "韓国・エスニック" },
  { name: "トムヤムクン", kcal: 200, category: "韓国・エスニック" },
  { name: "パッタイ", kcal: 550, category: "韓国・エスニック" },
  { name: "カオマンガイ", kcal: 600, category: "韓国・エスニック" },
  { name: "ナシゴレン", kcal: 600, category: "韓国・エスニック" },
  { name: "フォー", kcal: 400, category: "韓国・エスニック" },
  { name: "生春巻き（2本）", kcal: 150, category: "韓国・エスニック" },
  { name: "バインミー", kcal: 400, category: "韓国・エスニック" },
  { name: "ビリヤニ", kcal: 650, category: "韓国・エスニック" },
  { name: "バターチキンカレー", kcal: 750, category: "韓国・エスニック" },
  { name: "ナン（1枚）", kcal: 250, category: "韓国・エスニック" },
  { name: "タンドリーチキン（2本）", kcal: 300, category: "韓国・エスニック" },
  { name: "サモサ（2個）", kcal: 200, category: "韓国・エスニック" },
  { name: "タコス（2個）", kcal: 400, category: "韓国・エスニック" },
  { name: "ブリトー", kcal: 600, category: "韓国・エスニック" },
  { name: "ケバブ", kcal: 450, category: "韓国・エスニック" },

  // ══ ファストフード ═══════════════════════════
  // マクドナルド
  { name: "ビッグマック", kcal: 525, category: "ファストフード", sub: "マクドナルド" },
  { name: "ダブルチーズバーガー", kcal: 457, category: "ファストフード", sub: "マクドナルド" },
  { name: "チーズバーガー", kcal: 302, category: "ファストフード", sub: "マクドナルド" },
  { name: "ハンバーガー（マック）", kcal: 256, category: "ファストフード", sub: "マクドナルド" },
  { name: "てりやきマックバーガー", kcal: 473, category: "ファストフード", sub: "マクドナルド" },
  { name: "えびフィレオ", kcal: 395, category: "ファストフード", sub: "マクドナルド" },
  { name: "フィレオフィッシュ", kcal: 377, category: "ファストフード", sub: "マクドナルド" },
  { name: "チキンフィレオ", kcal: 465, category: "ファストフード", sub: "マクドナルド" },
  { name: "ベーコンレタスバーガー", kcal: 374, category: "ファストフード", sub: "マクドナルド" },
  { name: "グラコロ", kcal: 410, category: "ファストフード", sub: "マクドナルド" },
  { name: "月見バーガー", kcal: 410, category: "ファストフード", sub: "マクドナルド" },
  { name: "マックフライポテト（S）", kcal: 225, category: "ファストフード", sub: "マクドナルド" },
  { name: "マックフライポテト（M）", kcal: 410, category: "ファストフード", sub: "マクドナルド" },
  { name: "マックフライポテト（L）", kcal: 517, category: "ファストフード", sub: "マクドナルド" },
  { name: "チキンマックナゲット（5個）", kcal: 270, category: "ファストフード", sub: "マクドナルド" },
  { name: "スパイシーチキンマックナゲット（5個）", kcal: 290, category: "ファストフード", sub: "マクドナルド" },
  { name: "シャカチキ", kcal: 233, category: "ファストフード", sub: "マクドナルド" },
  { name: "ハッシュポテト", kcal: 146, category: "ファストフード", sub: "マクドナルド" },
  { name: "マックシェイク（M）", kcal: 430, category: "ファストフード", sub: "マクドナルド" },
  { name: "マックフルーリー", kcal: 250, category: "ファストフード", sub: "マクドナルド" },
  { name: "ソフトツイスト", kcal: 145, category: "ファストフード", sub: "マクドナルド" },
  { name: "マックアップルパイ", kcal: 240, category: "ファストフード", sub: "マクドナルド" },
  { name: "エッグマックマフィン", kcal: 303, category: "ファストフード", sub: "マクドナルド" },
  { name: "ソーセージマフィン", kcal: 370, category: "ファストフード", sub: "マクドナルド" },
  { name: "ホットケーキ（マック）", kcal: 460, category: "ファストフード", sub: "マクドナルド" },
  { name: "ビッグマックセット", kcal: 1075, category: "ファストフード", sub: "マクドナルド" },
  // モスバーガー
  { name: "モスバーガー", kcal: 417, category: "ファストフード", sub: "モスバーガー" },
  { name: "モスチーズバーガー", kcal: 473, category: "ファストフード", sub: "モスバーガー" },
  { name: "スパイシーモスバーガー", kcal: 437, category: "ファストフード", sub: "モスバーガー" },
  { name: "テリヤキバーガー（モス）", kcal: 380, category: "ファストフード", sub: "モスバーガー" },
  { name: "モスライスバーガー", kcal: 350, category: "ファストフード", sub: "モスバーガー" },
  { name: "モスフィッシュバーガー", kcal: 360, category: "ファストフード", sub: "モスバーガー" },
  { name: "ロースカツバーガー（モス）", kcal: 460, category: "ファストフード", sub: "モスバーガー" },
  { name: "モスチキン", kcal: 230, category: "ファストフード", sub: "モスバーガー" },
  { name: "モスポテト", kcal: 220, category: "ファストフード", sub: "モスバーガー" },
  { name: "オニオンフライ（モス）", kcal: 260, category: "ファストフード", sub: "モスバーガー" },
  // ケンタッキー
  { name: "オリジナルチキン（1ピース）", kcal: 237, category: "ファストフード", sub: "ケンタッキー" },
  { name: "骨なしケンタッキー", kcal: 204, category: "ファストフード", sub: "ケンタッキー" },
  { name: "サンダーチキン", kcal: 350, category: "ファストフード", sub: "ケンタッキー" },
  { name: "チキンフィレサンド", kcal: 415, category: "ファストフード", sub: "ケンタッキー" },
  { name: "和風チキンカツサンド", kcal: 460, category: "ファストフード", sub: "ケンタッキー" },
  { name: "カーネルクリスピー", kcal: 130, category: "ファストフード", sub: "ケンタッキー" },
  { name: "ナゲット（5個・KFC）", kcal: 230, category: "ファストフード", sub: "ケンタッキー" },
  { name: "ビスケット（KFC）", kcal: 200, category: "ファストフード", sub: "ケンタッキー" },
  { name: "ポテト（M・KFC）", kcal: 280, category: "ファストフード", sub: "ケンタッキー" },
  { name: "コールスロー（S・KFC）", kcal: 92, category: "ファストフード", sub: "ケンタッキー" },
  { name: "ケンタッキー2ピースセット", kcal: 700, category: "ファストフード", sub: "ケンタッキー" },
  // バーガーキング
  { name: "ワッパー", kcal: 640, category: "ファストフード", sub: "バーガーキング" },
  { name: "ワッパーチーズ", kcal: 710, category: "ファストフード", sub: "バーガーキング" },
  { name: "ダブルワッパー", kcal: 900, category: "ファストフード", sub: "バーガーキング" },
  { name: "ワッパージュニア", kcal: 380, category: "ファストフード", sub: "バーガーキング" },
  { name: "クリスピーチキン（BK）", kcal: 280, category: "ファストフード", sub: "バーガーキング" },
  { name: "オニオンリング（BK）", kcal: 320, category: "ファストフード", sub: "バーガーキング" },
  // ロッテリア・その他バーガー
  { name: "絶品チーズバーガー", kcal: 393, category: "ファストフード", sub: "ロッテリア・その他バーガー" },
  { name: "エビバーガー（ロッテリア）", kcal: 423, category: "ファストフード", sub: "ロッテリア・その他バーガー" },
  { name: "リブサンド（ビーフ）", kcal: 500, category: "ファストフード", sub: "ロッテリア・その他バーガー" },
  { name: "ぷるぷるホットケーキ", kcal: 380, category: "ファストフード", sub: "ロッテリア・その他バーガー" },
  { name: "フレッシュネスバーガー", kcal: 450, category: "ファストフード", sub: "ロッテリア・その他バーガー" },
  { name: "ドムドムハンバーガー", kcal: 350, category: "ファストフード", sub: "ロッテリア・その他バーガー" },
  { name: "クアアイナ アボカドバーガー", kcal: 700, category: "ファストフード", sub: "ロッテリア・その他バーガー" },
  // サブウェイ
  { name: "サブウェイ（BLT）", kcal: 360, category: "ファストフード", sub: "サブウェイ" },
  { name: "サブウェイ（ツナ）", kcal: 440, category: "ファストフード", sub: "サブウェイ" },
  { name: "サブウェイ（ローストチキン）", kcal: 320, category: "ファストフード", sub: "サブウェイ" },
  { name: "サブウェイ（てりやきチキン）", kcal: 360, category: "ファストフード", sub: "サブウェイ" },
  { name: "サブウェイ（えびアボカド）", kcal: 330, category: "ファストフード", sub: "サブウェイ" },
  // 牛丼・定食チェーン
  { name: "吉野家 牛丼（並）", kcal: 652, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "吉野家 牛丼（大盛）", kcal: 826, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "吉野家 チーズ牛丼（並）", kcal: 780, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "すき家 牛丼（並）", kcal: 680, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "すき家 チーズ牛丼（並）", kcal: 822, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "すき家 牛丼（大盛）", kcal: 875, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "松屋 牛めし（並）", kcal: 641, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "松屋 プレミアム牛めし（並）", kcal: 645, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "松屋 豚丼（並）", kcal: 690, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "松屋 カルビ定食", kcal: 800, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "なか卯 牛丼（並）", kcal: 615, category: "ファストフード", sub: "牛丼・定食チェーン" },
  { name: "なか卯 親子丼（並）", kcal: 670, category: "ファストフード", sub: "牛丼・定食チェーン" },
  // その他チェーン
  { name: "天丼てんや 天丼", kcal: 700, category: "ファストフード", sub: "その他チェーン" },
  { name: "丸亀製麺 かけうどん（並）", kcal: 290, category: "ファストフード", sub: "その他チェーン" },
  { name: "丸亀製麺 釜玉うどん（並）", kcal: 540, category: "ファストフード", sub: "その他チェーン" },
  { name: "はなまるうどん かけ（中）", kcal: 320, category: "ファストフード", sub: "その他チェーン" },
  { name: "CoCo壱 ポークカレー", kcal: 730, category: "ファストフード", sub: "その他チェーン" },
  { name: "CoCo壱 カツカレー", kcal: 1050, category: "ファストフード", sub: "その他チェーン" },
  { name: "リンガーハット ちゃんぽん", kcal: 660, category: "ファストフード", sub: "その他チェーン" },
  { name: "日高屋 中華そば", kcal: 430, category: "ファストフード", sub: "その他チェーン" },
  { name: "餃子の王将 餃子（6個）", kcal: 290, category: "ファストフード", sub: "その他チェーン" },
  // アイス・ドーナツ
  { name: "サーティワン（シングル）", kcal: 200, category: "ファストフード", sub: "アイス・ドーナツ" },
  { name: "サーティワン（ダブル）", kcal: 400, category: "ファストフード", sub: "アイス・ドーナツ" },
  { name: "ミスド ポンデリング", kcal: 220, category: "ファストフード", sub: "アイス・ドーナツ" },
  { name: "ミスド エンゼルクリーム", kcal: 230, category: "ファストフード", sub: "アイス・ドーナツ" },
  { name: "ミスド オールドファッション", kcal: 290, category: "ファストフード", sub: "アイス・ドーナツ" },

  // ══ コンビニ ════════════════════════════════
  { name: "コンビニ 幕の内弁当", kcal: 650, category: "コンビニ" },
  { name: "コンビニ から揚げ弁当", kcal: 850, category: "コンビニ" },
  { name: "コンビニ のり弁当", kcal: 600, category: "コンビニ" },
  { name: "コンビニ 焼肉弁当", kcal: 750, category: "コンビニ" },
  { name: "コンビニ チャーシュー弁当", kcal: 700, category: "コンビニ" },
  { name: "コンビニ 鮭弁当", kcal: 580, category: "コンビニ" },
  { name: "コンビニ ハンバーグ弁当", kcal: 780, category: "コンビニ" },
  { name: "コンビニ パスタ（ナポリタン）", kcal: 600, category: "コンビニ" },
  { name: "コンビニ パスタ（カルボナーラ）", kcal: 650, category: "コンビニ" },
  { name: "コンビニ 冷やし中華", kcal: 450, category: "コンビニ" },
  { name: "コンビニ ざるそば", kcal: 350, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（ミックス）", kcal: 380, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（ツナ）", kcal: 350, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（たまご）", kcal: 330, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（BLT）", kcal: 370, category: "コンビニ" },
  { name: "コンビニ サンドイッチ（カツ）", kcal: 480, category: "コンビニ" },
  { name: "コンビニ フルーツサンド", kcal: 350, category: "コンビニ" },
  { name: "コンビニ 肉まん", kcal: 230, category: "コンビニ" },
  { name: "コンビニ あんまん", kcal: 280, category: "コンビニ" },
  { name: "コンビニ ピザまん", kcal: 250, category: "コンビニ" },
  { name: "コンビニ カレーまん", kcal: 260, category: "コンビニ" },
  { name: "コンビニ からあげ棒", kcal: 190, category: "コンビニ" },
  { name: "コンビニ ファミチキ", kcal: 240, category: "コンビニ" },
  { name: "コンビニ アメリカンドッグ", kcal: 250, category: "コンビニ" },
  { name: "コンビニ フランクフルト", kcal: 260, category: "コンビニ" },
  { name: "コンビニ コロッケ", kcal: 200, category: "コンビニ" },
  { name: "コンビニ カップラーメン（醤油）", kcal: 350, category: "コンビニ" },
  { name: "コンビニ カップラーメン（塩）", kcal: 320, category: "コンビニ" },
  { name: "コンビニ カップラーメン（味噌）", kcal: 360, category: "コンビニ" },
  { name: "コンビニ カップ焼きそば", kcal: 480, category: "コンビニ" },
  { name: "コンビニ カップうどん", kcal: 300, category: "コンビニ" },
  { name: "コンビニ チルドラーメン", kcal: 500, category: "コンビニ" },
  { name: "コンビニ おでん（5品）", kcal: 250, category: "コンビニ" },
  { name: "コンビニ サラダチキン（プレーン）", kcal: 110, category: "コンビニ" },
  { name: "コンビニ サラダチキン（ハーブ）", kcal: 110, category: "コンビニ" },
  { name: "コンビニ サラダ（シーザー）", kcal: 150, category: "コンビニ" },
  { name: "コンビニ サラダ（和風）", kcal: 100, category: "コンビニ" },
  { name: "コンビニ パスタサラダ", kcal: 250, category: "コンビニ" },
  { name: "コンビニ ゆで卵（2個）", kcal: 150, category: "コンビニ" },
  { name: "コンビニ 6Pチーズ", kcal: 200, category: "コンビニ" },
  { name: "コンビニ プリン", kcal: 180, category: "コンビニ" },
  { name: "コンビニ シュークリーム", kcal: 230, category: "コンビニ" },
  { name: "コンビニ エクレア", kcal: 270, category: "コンビニ" },
  { name: "コンビニ ロールケーキ", kcal: 300, category: "コンビニ" },
  { name: "コンビニ バスチー", kcal: 250, category: "コンビニ" },
  { name: "コンビニ どらやき", kcal: 240, category: "コンビニ" },
  { name: "コンビニ わらび餅", kcal: 160, category: "コンビニ" },
  { name: "コンビニ ヨーグルト（小）", kcal: 100, category: "コンビニ" },

  // ══ パン ════════════════════════════════════
  { name: "食パン（1枚）", kcal: 160, category: "パン" },
  { name: "食パン（2枚）", kcal: 320, category: "パン" },
  { name: "トースト（1枚）", kcal: 180, category: "パン" },
  { name: "バタートースト（1枚）", kcal: 230, category: "パン" },
  { name: "ジャムトースト（1枚）", kcal: 210, category: "パン" },
  { name: "はちみつトースト", kcal: 280, category: "パン" },
  { name: "ガーリックトースト（1切れ）", kcal: 180, category: "パン" },
  { name: "ピザトースト（1枚）", kcal: 320, category: "パン" },
  { name: "クロワッサン（1個）", kcal: 230, category: "パン" },
  { name: "パン・オ・ショコラ", kcal: 330, category: "パン" },
  { name: "デニッシュ（1個）", kcal: 280, category: "パン" },
  { name: "メロンパン", kcal: 380, category: "パン" },
  { name: "クリームパン", kcal: 280, category: "パン" },
  { name: "カスタードクリームパン", kcal: 310, category: "パン" },
  { name: "あんパン", kcal: 300, category: "パン" },
  { name: "ホイップあんぱん", kcal: 350, category: "パン" },
  { name: "抹茶あんぱん", kcal: 310, category: "パン" },
  { name: "カレーパン", kcal: 350, category: "パン" },
  { name: "焼きカレーパン", kcal: 320, category: "パン" },
  { name: "コロネ（チョコ）", kcal: 280, category: "パン" },
  { name: "塩パン", kcal: 200, category: "パン" },
  { name: "明太フランス", kcal: 380, category: "パン" },
  { name: "ベーコンエピ", kcal: 340, category: "パン" },
  { name: "クロックムッシュ", kcal: 420, category: "パン" },
  { name: "マリトッツォ", kcal: 320, category: "パン" },
  { name: "フルーツサンド", kcal: 380, category: "パン" },
  { name: "カツサンド", kcal: 520, category: "パン" },
  { name: "たまごサンド", kcal: 320, category: "パン" },
  { name: "ハムサンド", kcal: 280, category: "パン" },
  { name: "ツナサンド", kcal: 300, category: "パン" },
  { name: "BLTサンド", kcal: 420, category: "パン" },
  { name: "ホットドッグ", kcal: 350, category: "パン" },
  { name: "ベーグル（プレーン）", kcal: 280, category: "パン" },
  { name: "ベーグルサンド", kcal: 380, category: "パン" },
  { name: "イングリッシュマフィン（1個）", kcal: 130, category: "パン" },
  { name: "フランスパン（1切れ）", kcal: 110, category: "パン" },
  { name: "バゲットサンド", kcal: 400, category: "パン" },
  { name: "ロールパン（1個）", kcal: 100, category: "パン" },
  { name: "バターロール（2個）", kcal: 200, category: "パン" },
  { name: "シナモンロール", kcal: 350, category: "パン" },
  { name: "ベーコンチーズパン", kcal: 360, category: "パン" },
  { name: "ソーセージパン", kcal: 330, category: "パン" },
  { name: "コーンマヨパン", kcal: 320, category: "パン" },
  { name: "ツナマヨパン", kcal: 340, category: "パン" },
  { name: "ピザパン", kcal: 340, category: "パン" },
  { name: "チーズパン", kcal: 260, category: "パン" },
  { name: "レーズンパン（1個）", kcal: 260, category: "パン" },
  { name: "黒糖パン（1個）", kcal: 250, category: "パン" },
  { name: "ライ麦パン（1切れ）", kcal: 140, category: "パン" },
  { name: "全粒粉パン（1切れ）", kcal: 150, category: "パン" },
  { name: "カンパーニュ（1切れ）", kcal: 130, category: "パン" },
  { name: "ブリオッシュ（1個）", kcal: 290, category: "パン" },
  { name: "コッペパン（ジャム）", kcal: 320, category: "パン" },
  { name: "コッペパン（ピーナッツ）", kcal: 380, category: "パン" },
  { name: "コッペパン（焼きそば）", kcal: 400, category: "パン" },
  { name: "アップルパイ（パン屋）", kcal: 380, category: "パン" },

  // ══ 惣菜（揚げ物・一品・小鉢）═══════════════════
  { name: "からあげ（1個）", kcal: 75, category: "惣菜" },
  { name: "からあげ（3個）", kcal: 225, category: "惣菜" },
  { name: "からあげ（5個）", kcal: 375, category: "惣菜" },
  { name: "鶏天（1個）", kcal: 80, category: "惣菜" },
  { name: "フライドチキン（1本）", kcal: 240, category: "惣菜" },
  { name: "チキンナゲット（5個）", kcal: 250, category: "惣菜" },
  { name: "コロッケ（1個）", kcal: 170, category: "惣菜" },
  { name: "カニクリームコロッケ（1個）", kcal: 150, category: "惣菜" },
  { name: "メンチカツ（1個）", kcal: 270, category: "惣菜" },
  { name: "とんかつ（1枚）", kcal: 450, category: "惣菜" },
  { name: "ヒレカツ（1枚）", kcal: 350, category: "惣菜" },
  { name: "串カツ（1本）", kcal: 100, category: "惣菜" },
  { name: "エビフライ（1本）", kcal: 90, category: "惣菜" },
  { name: "アジフライ（1枚）", kcal: 160, category: "惣菜" },
  { name: "イカリング（3個）", kcal: 150, category: "惣菜" },
  { name: "ちくわ天（1本）", kcal: 90, category: "惣菜" },
  { name: "天ぷら盛り合わせ", kcal: 400, category: "惣菜" },
  { name: "春巻き（1本）", kcal: 110, category: "惣菜" },
  { name: "餃子（5個）", kcal: 200, category: "惣菜" },
  { name: "焼売（3個）", kcal: 105, category: "惣菜" },
  { name: "ハンバーグ（1個）", kcal: 280, category: "惣菜" },
  { name: "煮込みハンバーグ（1個）", kcal: 350, category: "惣菜" },
  { name: "肉団子（5個）", kcal: 280, category: "惣菜" },
  { name: "つくね（1本）", kcal: 90, category: "惣菜" },
  { name: "卵焼き（2切れ）", kcal: 100, category: "惣菜" },
  { name: "だし巻き卵", kcal: 100, category: "惣菜" },
  { name: "枝豆（1皿）", kcal: 80, category: "惣菜" },
  { name: "冷やしトマト", kcal: 50, category: "惣菜" },
  { name: "揚げ出し豆腐", kcal: 200, category: "惣菜" },
  { name: "焼き鳥・もも（1本）", kcal: 95, category: "惣菜" },
  { name: "焼き鳥・ねぎま（1本）", kcal: 80, category: "惣菜" },
  { name: "焼き鳥・つくね（1本）", kcal: 110, category: "惣菜" },
  { name: "焼き鳥・皮（1本）", kcal: 120, category: "惣菜" },
  { name: "焼き鳥・砂肝（1本）", kcal: 40, category: "惣菜" },
  { name: "焼き鳥・レバー（1本）", kcal: 50, category: "惣菜" },
  { name: "焼き鳥・手羽先（1本）", kcal: 110, category: "惣菜" },
  { name: "焼き鳥・ぼんじり（1本）", kcal: 130, category: "惣菜" },
  { name: "肉じゃが（小鉢）", kcal: 180, category: "惣菜" },
  { name: "筑前煮（小鉢）", kcal: 120, category: "惣菜" },
  { name: "ひじき煮（小鉢）", kcal: 70, category: "惣菜" },
  { name: "きんぴらごぼう（小鉢）", kcal: 80, category: "惣菜" },
  { name: "切り干し大根（小鉢）", kcal: 80, category: "惣菜" },
  { name: "かぼちゃの煮物（小鉢）", kcal: 110, category: "惣菜" },
  { name: "大根の煮物（小鉢）", kcal: 70, category: "惣菜" },
  { name: "ほうれん草のおひたし（小鉢）", kcal: 40, category: "惣菜" },

  // ══ スーパー惣菜（弁当・パック）═══════════════
  { name: "スーパー 幕の内弁当", kcal: 680, category: "スーパー惣菜" },
  { name: "スーパー 唐揚げ弁当", kcal: 820, category: "スーパー惣菜" },
  { name: "スーパー のり弁当", kcal: 620, category: "スーパー惣菜" },
  { name: "スーパー 焼き魚弁当", kcal: 580, category: "スーパー惣菜" },
  { name: "スーパー チキン南蛮弁当", kcal: 750, category: "スーパー惣菜" },
  { name: "スーパー 焼肉弁当", kcal: 800, category: "スーパー惣菜" },
  { name: "スーパー ハンバーグ弁当", kcal: 780, category: "スーパー惣菜" },
  { name: "スーパー カルビ弁当", kcal: 870, category: "スーパー惣菜" },
  { name: "スーパー 親子丼弁当", kcal: 700, category: "スーパー惣菜" },
  { name: "スーパー カツ丼弁当", kcal: 850, category: "スーパー惣菜" },
  { name: "スーパー 天丼弁当", kcal: 780, category: "スーパー惣菜" },
  { name: "スーパー チャーハン弁当", kcal: 720, category: "スーパー惣菜" },
  { name: "スーパー 豚丼弁当", kcal: 720, category: "スーパー惣菜" },
  { name: "スーパー ビビンバ弁当", kcal: 650, category: "スーパー惣菜" },
  { name: "スーパー 寿司（並・8貫）", kcal: 440, category: "スーパー惣菜" },
  { name: "スーパー 寿司（上・8貫）", kcal: 500, category: "スーパー惣菜" },
  { name: "スーパー ちらし寿司パック", kcal: 550, category: "スーパー惣菜" },
  // 揚げ物パック
  { name: "スーパー とんかつ（1枚）", kcal: 430, category: "スーパー惣菜", sub: "揚げ物パック" },
  { name: "スーパー コロッケ（2個）", kcal: 320, category: "スーパー惣菜", sub: "揚げ物パック" },
  { name: "スーパー メンチカツ（1個）", kcal: 260, category: "スーパー惣菜", sub: "揚げ物パック" },
  { name: "スーパー エビフライ（3本）", kcal: 300, category: "スーパー惣菜", sub: "揚げ物パック" },
  { name: "スーパー 唐揚げ（5個）", kcal: 400, category: "スーパー惣菜", sub: "揚げ物パック" },
  { name: "スーパー 春巻き（2本）", kcal: 260, category: "スーパー惣菜", sub: "揚げ物パック" },
  { name: "スーパー チキンカツ（1枚）", kcal: 380, category: "スーパー惣菜", sub: "揚げ物パック" },
  { name: "スーパー 餃子（6個）", kcal: 290, category: "スーパー惣菜", sub: "揚げ物パック" },
  // 焼き魚パック
  { name: "スーパー さば塩焼き（1切れ）", kcal: 230, category: "スーパー惣菜", sub: "焼き魚パック" },
  { name: "スーパー 鮭塩焼き（1切れ）", kcal: 200, category: "スーパー惣菜", sub: "焼き魚パック" },
  { name: "スーパー ほっけ塩焼き（1枚）", kcal: 280, category: "スーパー惣菜", sub: "焼き魚パック" },
  { name: "スーパー さばの味噌煮（1切れ）", kcal: 250, category: "スーパー惣菜", sub: "焼き魚パック" },
  { name: "スーパー 西京焼き（さば）", kcal: 260, category: "スーパー惣菜", sub: "焼き魚パック" },
  // 中華・韓国パック
  { name: "スーパー 麻婆豆腐（パック）", kcal: 220, category: "スーパー惣菜", sub: "中華・韓国パック" },
  { name: "スーパー 酢豚（パック）", kcal: 280, category: "スーパー惣菜", sub: "中華・韓国パック" },
  { name: "スーパー 八宝菜（パック）", kcal: 200, category: "スーパー惣菜", sub: "中華・韓国パック" },
  { name: "スーパー エビチリ（パック）", kcal: 230, category: "スーパー惣菜", sub: "中華・韓国パック" },
  { name: "スーパー 回鍋肉（パック）", kcal: 310, category: "スーパー惣菜", sub: "中華・韓国パック" },
  { name: "スーパー チンジャオロース（パック）", kcal: 260, category: "スーパー惣菜", sub: "中華・韓国パック" },
  { name: "スーパー プルコギ（パック）", kcal: 350, category: "スーパー惣菜", sub: "中華・韓国パック" },
  { name: "スーパー チャプチェ（パック）", kcal: 240, category: "スーパー惣菜", sub: "中華・韓国パック" },
  // 肉・主菜パック
  { name: "スーパー 照り焼きチキン（1枚）", kcal: 300, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー ローストビーフ（3切れ）", kcal: 200, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー 豚の角煮（パック）", kcal: 450, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー スペアリブ（2本）", kcal: 420, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー ハンバーグ（1個）", kcal: 290, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー 煮込みハンバーグ（1個）", kcal: 350, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー ロールキャベツ（2個）", kcal: 280, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー 肉団子甘酢あん（5個）", kcal: 310, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー シュウマイ（5個）", kcal: 230, category: "スーパー惣菜", sub: "肉・主菜パック" },
  { name: "スーパー 小籠包（5個）", kcal: 260, category: "スーパー惣菜", sub: "肉・主菜パック" },
  // 練り物
  { name: "スーパー かまぼこ（1/2本）", kcal: 100, category: "スーパー惣菜", sub: "練り物" },
  { name: "スーパー ちくわ（2本）", kcal: 70, category: "スーパー惣菜", sub: "練り物" },
  { name: "スーパー はんぺん（1枚）", kcal: 95, category: "スーパー惣菜", sub: "練り物" },
  { name: "スーパー さつま揚げ（1枚）", kcal: 90, category: "スーパー惣菜", sub: "練り物" },
  { name: "スーパー 笹かまぼこ（2枚）", kcal: 80, category: "スーパー惣菜", sub: "練り物" },
  // 洋食・サラダパック
  { name: "スーパー グラタン（1個）", kcal: 350, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー ドリア（1パック）", kcal: 400, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー ラザニア（1パック）", kcal: 420, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー ミートボール（5個）", kcal: 280, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー ポテトサラダ（パック）", kcal: 150, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー マカロニサラダ（パック）", kcal: 160, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー ごぼうサラダ（パック）", kcal: 130, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー 春雨サラダ（パック）", kcal: 120, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー 中華サラダ（パック）", kcal: 120, category: "スーパー惣菜", sub: "洋食・サラダパック" },
  { name: "スーパー 海藻サラダ（パック）", kcal: 40, category: "スーパー惣菜", sub: "洋食・サラダパック" },

  // ══ サラダ・野菜 ═══════════════════════════════
  { name: "シーザーサラダ", kcal: 250, category: "サラダ・野菜" },
  { name: "グリーンサラダ", kcal: 80, category: "サラダ・野菜" },
  { name: "コブサラダ", kcal: 300, category: "サラダ・野菜" },
  { name: "ニース風サラダ", kcal: 280, category: "サラダ・野菜" },
  { name: "ポテトサラダ", kcal: 200, category: "サラダ・野菜" },
  { name: "コールスロー", kcal: 150, category: "サラダ・野菜" },
  { name: "海藻サラダ", kcal: 60, category: "サラダ・野菜" },
  { name: "大根サラダ", kcal: 70, category: "サラダ・野菜" },
  { name: "トマトサラダ", kcal: 60, category: "サラダ・野菜" },
  { name: "アボカドサラダ", kcal: 180, category: "サラダ・野菜" },
  { name: "チキンサラダ", kcal: 200, category: "サラダ・野菜" },
  { name: "シーフードサラダ", kcal: 180, category: "サラダ・野菜" },
  { name: "豆腐サラダ", kcal: 150, category: "サラダ・野菜" },
  { name: "ほうれん草のソテー", kcal: 80, category: "サラダ・野菜" },
  { name: "野菜炒め", kcal: 150, category: "サラダ・野菜" },
  { name: "温野菜（蒸し野菜）", kcal: 120, category: "サラダ・野菜" },
  { name: "ブロッコリー（1房）", kcal: 30, category: "サラダ・野菜" },

  // ══ 肉・魚（食材 100g など）════════════════════
  { name: "鶏むね肉（100g）", kcal: 105, category: "肉・魚" },
  { name: "鶏もも肉（100g）", kcal: 200, category: "肉・魚" },
  { name: "ささみ（100g）", kcal: 105, category: "肉・魚" },
  { name: "豚ロース（100g）", kcal: 263, category: "肉・魚" },
  { name: "豚バラ（100g）", kcal: 395, category: "肉・魚" },
  { name: "豚ヒレ（100g）", kcal: 130, category: "肉・魚" },
  { name: "牛ロース（100g）", kcal: 380, category: "肉・魚" },
  { name: "牛もも（100g）", kcal: 180, category: "肉・魚" },
  { name: "牛ひき肉（100g）", kcal: 250, category: "肉・魚" },
  { name: "鶏ひき肉（100g）", kcal: 170, category: "肉・魚" },
  { name: "ラム肉（100g）", kcal: 230, category: "肉・魚" },
  { name: "サーモン（100g）", kcal: 170, category: "肉・魚" },
  { name: "マグロ赤身（100g）", kcal: 125, category: "肉・魚" },
  { name: "ブリ（100g）", kcal: 250, category: "肉・魚" },
  { name: "さば（100g）", kcal: 210, category: "肉・魚" },
  { name: "さんま（1尾）", kcal: 260, category: "肉・魚" },
  { name: "あじ（1尾）", kcal: 120, category: "肉・魚" },
  { name: "いわし（1尾）", kcal: 110, category: "肉・魚" },
  { name: "エビ（100g）", kcal: 80, category: "肉・魚" },
  { name: "ホタテ（100g）", kcal: 70, category: "肉・魚" },
  { name: "イカ（100g）", kcal: 75, category: "肉・魚" },
  { name: "タコ（100g）", kcal: 80, category: "肉・魚" },
  { name: "あさり（100g）", kcal: 30, category: "肉・魚" },
  { name: "ベーコン（2枚）", kcal: 130, category: "肉・魚" },
  { name: "ウインナー（2本）", kcal: 160, category: "肉・魚" },
  { name: "ハム（2枚）", kcal: 80, category: "肉・魚" },
  { name: "鶏レバー（100g）", kcal: 110, category: "肉・魚" },

  // ══ 乳製品・卵 ═════════════════════════════════
  { name: "ヨーグルト（加糖・100g）", kcal: 65, category: "乳製品・卵" },
  { name: "ヨーグルト（無糖・150g）", kcal: 85, category: "乳製品・卵" },
  { name: "ギリシャヨーグルト（100g）", kcal: 70, category: "乳製品・卵" },
  { name: "飲むヨーグルト（200ml）", kcal: 120, category: "乳製品・卵" },
  { name: "スライスチーズ（1枚）", kcal: 70, category: "乳製品・卵" },
  { name: "カマンベールチーズ（30g）", kcal: 95, category: "乳製品・卵" },
  { name: "モッツァレラチーズ（50g）", kcal: 125, category: "乳製品・卵" },
  { name: "クリームチーズ（30g）", kcal: 100, category: "乳製品・卵" },
  { name: "プロセスチーズ（1個）", kcal: 60, category: "乳製品・卵" },
  { name: "牛乳（コップ1杯）", kcal: 135, category: "乳製品・卵" },
  { name: "低脂肪乳（200ml）", kcal: 90, category: "乳製品・卵" },
  { name: "生クリーム（大さじ1）", kcal: 50, category: "乳製品・卵" },
  { name: "バター（1かけ）", kcal: 75, category: "乳製品・卵" },
  { name: "ゆで卵（1個）", kcal: 75, category: "乳製品・卵" },
  { name: "温泉卵（1個）", kcal: 70, category: "乳製品・卵" },
  { name: "生卵（1個）", kcal: 75, category: "乳製品・卵" },

  // ══ 果物 ═══════════════════════════════════════
  { name: "バナナ（1本）", kcal: 90, category: "果物" },
  { name: "りんご（1個）", kcal: 150, category: "果物" },
  { name: "みかん（1個）", kcal: 45, category: "果物" },
  { name: "オレンジ（1個）", kcal: 80, category: "果物" },
  { name: "グレープフルーツ（1/2個）", kcal: 60, category: "果物" },
  { name: "いちご（10粒）", kcal: 40, category: "果物" },
  { name: "ぶどう（1房）", kcal: 120, category: "果物" },
  { name: "シャインマスカット（1房）", kcal: 140, category: "果物" },
  { name: "スイカ（1切れ）", kcal: 90, category: "果物" },
  { name: "メロン（1切れ）", kcal: 80, category: "果物" },
  { name: "桃（1個）", kcal: 75, category: "果物" },
  { name: "梨（1個）", kcal: 100, category: "果物" },
  { name: "キウイ（1個）", kcal: 55, category: "果物" },
  { name: "マンゴー（1/2個）", kcal: 100, category: "果物" },
  { name: "パイナップル（1切れ）", kcal: 60, category: "果物" },
  { name: "柿（1個）", kcal: 120, category: "果物" },
  { name: "ブルーベリー（1カップ）", kcal: 80, category: "果物" },
  { name: "さくらんぼ（10粒）", kcal: 45, category: "果物" },
  { name: "いちじく（1個）", kcal: 40, category: "果物" },
  { name: "アボカド（1個）", kcal: 260, category: "果物" },
  { name: "ライチ（5個）", kcal: 30, category: "果物" },
  { name: "デコポン（1個）", kcal: 60, category: "果物" },
  { name: "干し柿（1個）", kcal: 100, category: "果物" },
  { name: "プルーン（3個）", kcal: 70, category: "果物" },
  { name: "レーズン（大さじ1）", kcal: 40, category: "果物" },

  // ══ お菓子 ═════════════════════════════════════
  // 洋菓子
  { name: "ショートケーキ", kcal: 340, category: "お菓子", sub: "洋菓子" },
  { name: "チョコレートケーキ", kcal: 420, category: "お菓子", sub: "洋菓子" },
  { name: "チーズケーキ", kcal: 300, category: "お菓子", sub: "洋菓子" },
  { name: "レアチーズケーキ", kcal: 280, category: "お菓子", sub: "洋菓子" },
  { name: "ガトーショコラ", kcal: 320, category: "お菓子", sub: "洋菓子" },
  { name: "モンブラン", kcal: 340, category: "お菓子", sub: "洋菓子" },
  { name: "ミルフィーユ", kcal: 350, category: "お菓子", sub: "洋菓子" },
  { name: "フルーツタルト", kcal: 300, category: "お菓子", sub: "洋菓子" },
  { name: "アップルパイ（1切れ）", kcal: 300, category: "お菓子", sub: "洋菓子" },
  { name: "シュークリーム", kcal: 180, category: "お菓子", sub: "洋菓子" },
  { name: "エクレア", kcal: 200, category: "お菓子", sub: "洋菓子" },
  { name: "プリン", kcal: 130, category: "お菓子", sub: "洋菓子" },
  { name: "プリンアラモード", kcal: 280, category: "お菓子", sub: "洋菓子" },
  { name: "パンナコッタ", kcal: 180, category: "お菓子", sub: "洋菓子" },
  { name: "クレームブリュレ", kcal: 250, category: "お菓子", sub: "洋菓子" },
  { name: "ゼリー（1個）", kcal: 70, category: "お菓子", sub: "洋菓子" },
  { name: "杏仁豆腐", kcal: 130, category: "お菓子", sub: "洋菓子" },
  { name: "ティラミス", kcal: 250, category: "お菓子", sub: "洋菓子" },
  { name: "パフェ", kcal: 450, category: "お菓子", sub: "洋菓子" },
  { name: "クレープ（1個）", kcal: 280, category: "お菓子", sub: "洋菓子" },
  { name: "マカロン（1個）", kcal: 90, category: "お菓子", sub: "洋菓子" },
  { name: "フィナンシェ（1個）", kcal: 130, category: "お菓子", sub: "洋菓子" },
  { name: "マドレーヌ（1個）", kcal: 120, category: "お菓子", sub: "洋菓子" },
  { name: "バウムクーヘン（1切れ）", kcal: 180, category: "お菓子", sub: "洋菓子" },
  { name: "カステラ（1切れ）", kcal: 160, category: "お菓子", sub: "洋菓子" },
  { name: "ワッフル（1個）", kcal: 200, category: "お菓子", sub: "洋菓子" },
  { name: "スコーン（1個）", kcal: 230, category: "お菓子", sub: "洋菓子" },
  { name: "ロールケーキ（1切れ）", kcal: 200, category: "お菓子", sub: "洋菓子" },
  { name: "クッキー（1枚）", kcal: 50, category: "お菓子", sub: "洋菓子" },
  { name: "ビスケット（1枚）", kcal: 45, category: "お菓子", sub: "洋菓子" },
  { name: "クラッカー（1枚）", kcal: 20, category: "お菓子", sub: "洋菓子" },
  { name: "ラスク（2枚）", kcal: 100, category: "お菓子", sub: "洋菓子" },
  { name: "チュロス（1本）", kcal: 150, category: "お菓子", sub: "洋菓子" },
  { name: "ドーナツ（1個）", kcal: 230, category: "お菓子", sub: "洋菓子" },
  { name: "オールドファッション（1個）", kcal: 290, category: "お菓子", sub: "洋菓子" },
  { name: "ポンデリング（1個）", kcal: 220, category: "お菓子", sub: "洋菓子" },
  { name: "チョコファッション（1個）", kcal: 330, category: "お菓子", sub: "洋菓子" },
  { name: "シュガードーナツ（1個）", kcal: 250, category: "お菓子", sub: "洋菓子" },
  // 和菓子
  { name: "どら焼き（1個）", kcal: 240, category: "お菓子", sub: "和菓子" },
  { name: "たい焼き（1個）", kcal: 200, category: "お菓子", sub: "和菓子" },
  { name: "大福（1個）", kcal: 170, category: "お菓子", sub: "和菓子" },
  { name: "いちご大福（1個）", kcal: 160, category: "お菓子", sub: "和菓子" },
  { name: "豆大福（1個）", kcal: 180, category: "お菓子", sub: "和菓子" },
  { name: "みたらし団子（1本）", kcal: 120, category: "お菓子", sub: "和菓子" },
  { name: "あんこ団子（1本）", kcal: 130, category: "お菓子", sub: "和菓子" },
  { name: "三色団子（1本）", kcal: 120, category: "お菓子", sub: "和菓子" },
  { name: "おはぎ（1個）", kcal: 180, category: "お菓子", sub: "和菓子" },
  { name: "まんじゅう（1個）", kcal: 140, category: "お菓子", sub: "和菓子" },
  { name: "もみじ饅頭（1個）", kcal: 100, category: "お菓子", sub: "和菓子" },
  { name: "羊羹（1切れ）", kcal: 150, category: "お菓子", sub: "和菓子" },
  { name: "水羊羹（1個）", kcal: 110, category: "お菓子", sub: "和菓子" },
  { name: "わらび餅（1人前）", kcal: 160, category: "お菓子", sub: "和菓子" },
  { name: "くずもち（1人前）", kcal: 140, category: "お菓子", sub: "和菓子" },
  { name: "あんみつ", kcal: 220, category: "お菓子", sub: "和菓子" },
  { name: "みつ豆", kcal: 180, category: "お菓子", sub: "和菓子" },
  { name: "白玉ぜんざい", kcal: 280, category: "お菓子", sub: "和菓子" },
  { name: "おしるこ", kcal: 250, category: "お菓子", sub: "和菓子" },
  { name: "今川焼き（1個）", kcal: 200, category: "お菓子", sub: "和菓子" },
  { name: "きんつば（1個）", kcal: 140, category: "お菓子", sub: "和菓子" },
  { name: "練り切り（1個）", kcal: 120, category: "お菓子", sub: "和菓子" },
  { name: "せんべい（1枚）", kcal: 60, category: "お菓子", sub: "和菓子" },
  { name: "ぬれせんべい（1枚）", kcal: 50, category: "お菓子", sub: "和菓子" },
  { name: "おかき（5個）", kcal: 100, category: "お菓子", sub: "和菓子" },
  { name: "あられ（一掴み）", kcal: 90, category: "お菓子", sub: "和菓子" },
  { name: "かりんとう（10本）", kcal: 130, category: "お菓子", sub: "和菓子" },
  { name: "芋けんぴ（一掴み）", kcal: 150, category: "お菓子", sub: "和菓子" },
  { name: "大学芋（小鉢）", kcal: 200, category: "お菓子", sub: "和菓子" },
  { name: "甘栗（1袋）", kcal: 150, category: "お菓子", sub: "和菓子" },
  // スナック・駄菓子
  { name: "ポテトチップス（1袋60g）", kcal: 340, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "ポテトチップス（小袋）", kcal: 170, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "プリングルズ（1筒）", kcal: 800, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "じゃがりこ（1カップ）", kcal: 300, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "かっぱえびせん（1袋）", kcal: 260, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "ベビースターラーメン（1袋）", kcal: 290, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "チートス（1袋）", kcal: 280, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "ポップコーン（1袋）", kcal: 300, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "柿の種（1袋）", kcal: 160, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "ミックスナッツ（一掴み）", kcal: 180, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "アーモンド（10粒）", kcal: 60, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "うまい棒（1本）", kcal: 40, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "ハイチュウ（1個）", kcal: 20, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "グミ（1袋）", kcal: 180, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "マシュマロ（1個）", kcal: 15, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "ラムネ菓子（1袋）", kcal: 40, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "飴（1個）", kcal: 15, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "のど飴（1個）", kcal: 13, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "キャラメル（1個）", kcal: 20, category: "お菓子", sub: "スナック・駄菓子" },
  { name: "ドライフルーツ（一掴み）", kcal: 100, category: "お菓子", sub: "スナック・駄菓子" },
  // チョコ
  { name: "板チョコ（1/2枚）", kcal: 140, category: "お菓子", sub: "チョコ" },
  { name: "チョコレート（1かけ）", kcal: 30, category: "お菓子", sub: "チョコ" },
  { name: "ビターチョコ（1かけ）", kcal: 28, category: "お菓子", sub: "チョコ" },
  { name: "生チョコ（1個）", kcal: 50, category: "お菓子", sub: "チョコ" },
  { name: "トリュフチョコ（1個）", kcal: 60, category: "お菓子", sub: "チョコ" },
  { name: "チョコボール（1箱）", kcal: 130, category: "お菓子", sub: "チョコ" },
  { name: "ポッキー（1袋）", kcal: 180, category: "お菓子", sub: "チョコ" },
  { name: "プリッツ（1袋）", kcal: 150, category: "お菓子", sub: "チョコ" },
  { name: "コアラのマーチ（1箱）", kcal: 250, category: "お菓子", sub: "チョコ" },
  { name: "きのこの山（1箱）", kcal: 420, category: "お菓子", sub: "チョコ" },
  { name: "たけのこの里（1箱）", kcal: 380, category: "お菓子", sub: "チョコ" },
  { name: "アルフォート（1個）", kcal: 50, category: "お菓子", sub: "チョコ" },
  { name: "ガルボ（1袋）", kcal: 290, category: "お菓子", sub: "チョコ" },
  { name: "ダース（1箱）", kcal: 250, category: "お菓子", sub: "チョコ" },
  // アイス
  { name: "ハーゲンダッツ（1個）", kcal: 250, category: "お菓子", sub: "アイス" },
  { name: "ソフトクリーム", kcal: 220, category: "お菓子", sub: "アイス" },
  { name: "アイスクリーム（バニラ）", kcal: 180, category: "お菓子", sub: "アイス" },
  { name: "アイスクリーム（チョコ）", kcal: 200, category: "お菓子", sub: "アイス" },
  { name: "ジェラート（1個）", kcal: 170, category: "お菓子", sub: "アイス" },
  { name: "かき氷（シロップ）", kcal: 120, category: "お菓子", sub: "アイス" },
  { name: "アイスモナカ（1個）", kcal: 230, category: "お菓子", sub: "アイス" },
  { name: "アイスバー（1本）", kcal: 110, category: "お菓子", sub: "アイス" },
  { name: "ガリガリ君（1本）", kcal: 70, category: "お菓子", sub: "アイス" },
  { name: "雪見だいふく（2個）", kcal: 170, category: "お菓子", sub: "アイス" },
  { name: "ピノ（1箱6粒）", kcal: 190, category: "お菓子", sub: "アイス" },
  { name: "パピコ（1本）", kcal: 85, category: "お菓子", sub: "アイス" },
  { name: "チョコモナカジャンボ", kcal: 300, category: "お菓子", sub: "アイス" },
  { name: "スーパーカップ（バニラ）", kcal: 380, category: "お菓子", sub: "アイス" },

  // ══ 飲み物 ═════════════════════════════════════
  // コーヒー・カフェ
  { name: "コーヒー（ブラック）", kcal: 5, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "エスプレッソ", kcal: 5, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "アメリカーノ", kcal: 10, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "微糖コーヒー（缶）", kcal: 50, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "加糖コーヒー（缶）", kcal: 80, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "カフェオレ", kcal: 100, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "カフェラテ（M）", kcal: 170, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "カフェラテ（L）", kcal: 220, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "カプチーノ", kcal: 130, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "カフェモカ", kcal: 260, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "キャラメルマキアート", kcal: 280, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "ソイラテ", kcal: 180, category: "飲み物", sub: "コーヒー・カフェ" },
  { name: "オーツミルクラテ", kcal: 170, category: "飲み物", sub: "コーヒー・カフェ" },
  // 茶・ラテ
  { name: "抹茶ラテ", kcal: 200, category: "飲み物", sub: "茶・ラテ" },
  { name: "ほうじ茶ラテ", kcal: 180, category: "飲み物", sub: "茶・ラテ" },
  { name: "チャイラテ", kcal: 220, category: "飲み物", sub: "茶・ラテ" },
  { name: "ロイヤルミルクティー", kcal: 250, category: "飲み物", sub: "茶・ラテ" },
  { name: "ミルクティー（500ml）", kcal: 200, category: "飲み物", sub: "茶・ラテ" },
  { name: "レモンティー", kcal: 90, category: "飲み物", sub: "茶・ラテ" },
  { name: "紅茶（無糖）", kcal: 5, category: "飲み物", sub: "茶・ラテ" },
  { name: "緑茶（無糖）", kcal: 0, category: "飲み物", sub: "茶・ラテ" },
  { name: "麦茶（無糖）", kcal: 0, category: "飲み物", sub: "茶・ラテ" },
  { name: "ほうじ茶（無糖）", kcal: 0, category: "飲み物", sub: "茶・ラテ" },
  { name: "ウーロン茶（無糖）", kcal: 0, category: "飲み物", sub: "茶・ラテ" },
  { name: "水", kcal: 0, category: "飲み物", sub: "茶・ラテ" },
  { name: "炭酸水（無糖）", kcal: 0, category: "飲み物", sub: "茶・ラテ" },
  // 炭酸・ジュース
  { name: "コカ・コーラ（500ml）", kcal: 225, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "コーラ ゼロ（500ml）", kcal: 0, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "ペプシ（500ml）", kcal: 225, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "ファンタ（500ml）", kcal: 230, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "スプライト（500ml）", kcal: 210, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "三ツ矢サイダー（500ml）", kcal: 220, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "ジンジャーエール（350ml）", kcal: 140, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "メロンソーダ（350ml）", kcal: 160, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "オレンジジュース（200ml）", kcal: 90, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "りんごジュース（200ml）", kcal: 90, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "ぶどうジュース（200ml）", kcal: 100, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "トマトジュース（200ml）", kcal: 40, category: "飲み物", sub: "炭酸・ジュース" },
  { name: "野菜ジュース（200ml）", kcal: 70, category: "飲み物", sub: "炭酸・ジュース" },
  // 乳・植物性飲料
  { name: "牛乳（200ml）", kcal: 135, category: "飲み物", sub: "乳・植物性飲料" },
  { name: "豆乳（200ml）", kcal: 110, category: "飲み物", sub: "乳・植物性飲料" },
  { name: "調整豆乳（200ml）", kcal: 120, category: "飲み物", sub: "乳・植物性飲料" },
  { name: "アーモンドミルク（200ml）", kcal: 60, category: "飲み物", sub: "乳・植物性飲料" },
  { name: "ココア（200ml）", kcal: 180, category: "飲み物", sub: "乳・植物性飲料" },
  { name: "ホットチョコレート", kcal: 320, category: "飲み物", sub: "乳・植物性飲料" },
  { name: "甘酒（200ml）", kcal: 100, category: "飲み物", sub: "乳・植物性飲料" },
  // スポーツ・エナジー
  { name: "スポーツドリンク（500ml）", kcal: 125, category: "飲み物", sub: "スポーツ・エナジー" },
  { name: "アクエリアス（500ml）", kcal: 100, category: "飲み物", sub: "スポーツ・エナジー" },
  { name: "ポカリスエット（500ml）", kcal: 130, category: "飲み物", sub: "スポーツ・エナジー" },
  { name: "経口補水液（500ml）", kcal: 50, category: "飲み物", sub: "スポーツ・エナジー" },
  { name: "エナジードリンク（モンスター355ml）", kcal: 160, category: "飲み物", sub: "スポーツ・エナジー" },
  { name: "レッドブル（250ml）", kcal: 115, category: "飲み物", sub: "スポーツ・エナジー" },
  { name: "プロテインシェイク", kcal: 200, category: "飲み物", sub: "スポーツ・エナジー" },
  { name: "プロテイン（水割り）", kcal: 120, category: "飲み物", sub: "スポーツ・エナジー" },
  // 流行り・スムージー・タピオカ
  { name: "レモネード", kcal: 150, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "スムージー（フルーツ）", kcal: 250, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "グリーンスムージー", kcal: 180, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "アサイースムージー", kcal: 260, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "バナナジュース（M）", kcal: 320, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "いちごミルク", kcal: 250, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "タピオカミルクティー（M）", kcal: 350, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "タピオカミルクティー（L）", kcal: 450, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "タピオカ抹茶ラテ", kcal: 380, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "黒糖タピオカミルク", kcal: 480, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "チーズティー", kcal: 280, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "フラペチーノ（コーヒー）", kcal: 320, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "フラペチーノ（抹茶）", kcal: 440, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "フラペチーノ（キャラメル）", kcal: 380, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "フラペチーノ（チョコ）", kcal: 480, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "いちごフラペチーノ", kcal: 360, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  { name: "コンブチャ（200ml）", kcal: 40, category: "飲み物", sub: "流行り・スムージー・タピオカ" },
  // お酒
  { name: "ビール（350ml）", kcal: 150, category: "飲み物", sub: "お酒" },
  { name: "ビール（500ml）", kcal: 215, category: "飲み物", sub: "お酒" },
  { name: "発泡酒（350ml）", kcal: 140, category: "飲み物", sub: "お酒" },
  { name: "ハイボール（350ml）", kcal: 100, category: "飲み物", sub: "お酒" },
  { name: "レモンサワー（350ml）", kcal: 150, category: "飲み物", sub: "お酒" },
  { name: "チューハイ（350ml）", kcal: 160, category: "飲み物", sub: "お酒" },
  { name: "赤ワイン（グラス1杯）", kcal: 90, category: "飲み物", sub: "お酒" },
  { name: "白ワイン（グラス1杯）", kcal: 85, category: "飲み物", sub: "お酒" },
  { name: "日本酒（1合）", kcal: 200, category: "飲み物", sub: "お酒" },
  { name: "焼酎ロック（1杯）", kcal: 130, category: "飲み物", sub: "お酒" },
  { name: "焼酎水割り（1杯）", kcal: 90, category: "飲み物", sub: "お酒" },
  { name: "梅酒ロック（1杯）", kcal: 110, category: "飲み物", sub: "お酒" },
  { name: "ウイスキーロック（1杯）", kcal: 110, category: "飲み物", sub: "お酒" },
  { name: "ジントニック", kcal: 170, category: "飲み物", sub: "お酒" },
  { name: "カシスオレンジ", kcal: 170, category: "飲み物", sub: "お酒" },
  { name: "モヒート", kcal: 160, category: "飲み物", sub: "お酒" },
  { name: "モスコミュール", kcal: 180, category: "飲み物", sub: "お酒" },
  { name: "ノンアルコールビール（350ml）", kcal: 50, category: "飲み物", sub: "お酒" },
  { name: "ノンアルコールチューハイ（350ml）", kcal: 30, category: "飲み物", sub: "お酒" },
];

// カテゴリ別に取得（「カテゴリから選ぶ」用）
export function getFoodsByCategory(category: string): FoodItem[] {
  return FOOD_DATABASE.filter((f) => f.category === category);
}

export function searchFoods(query: string): FoodItem[] {
  if (!query.trim()) return [];
  const q = query.trim();
  // 前方一致を優先、次に部分一致
  const exact = FOOD_DATABASE.filter(f => f.name.startsWith(q));
  const partial = FOOD_DATABASE.filter(f => !f.name.startsWith(q) && f.name.includes(q));
  return [...exact, ...partial].slice(0, 30);
}
